// ====== DALIL DB — HADIS, ATSAR, KITAB ======
var DALIL_H = {
"h-niat":{t:"h",ttl:"Hadis niat",
ar:"إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى",
tr:"\"Sesungguhnya amal-amal itu hanyalah (bergantung) pada niat-niatnya, dan setiap orang hanya memperoleh apa yang ia niatkan.\" (dari Umar bin Khattab)",
takhrij:"HR Bukhari no. 1 (hadis pembuka Sahih-nya) dan Muslim no. 1907.",
grade:"Sahih — muttafaqun 'alaih; Imam Syafi'i dan Ahmad menyebutnya mencakup sepertiga ilmu.",
sabab:"Tidak ada asbabul wurud yang tegas lagi sahih; kisah populer \"muhajir Ummu Qais\" diriwayatkan mauquf dari Ibnu Mas'ud dan tidak tegas sebagai sebab sabda ini (lihat pembahasan Ibnu Hajar dalam Fath al-Bari).",
syarah:"Ibnu Rajab (Jami' al-'Ulum wal-Hikam): niat membedakan ibadah dari kebiasaan dan membedakan derajat amal. Maka rutinitas mengasuh — menyusui, mengganti popok, membacakan buku — menjadi ibadah bila diniatkan karena Allah.",
note:"Pondasi seluruh kurikulum: meluruskan niat sebelum teknik apa pun."},

"h-istiqamah":{t:"h",ttl:"Amal yang paling dicintai: ajek meski sedikit",
ar:"أَحَبُّ الْأَعْمَالِ إِلَى اللَّهِ تَعَالَى أَدْوَمُهَا وَإِنْ قَلَّ",
tr:"\"Amal yang paling dicintai Allah Ta'ala adalah yang paling terus-menerus (kontinu) meskipun sedikit.\" (dari Aisyah)",
takhrij:"HR Bukhari no. 6464 dan Muslim no. 782/783.",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Aisyah ditanya tentang amal Nabi ﷺ; ia menjawab bahwa amal beliau berkesinambungan (dimah), lalu menyebut sabda ini — konteksnya menjelaskan pola ibadah beliau.",
syarah:"Ibnu Hajar (Fath al-Bari): amal sedikit yang kontinu melanggengkan ketaatan, dzikir, dan keikhlasan, sehingga buahnya melampaui amal banyak yang terputus.",
note:"Dasar ritme harian: pilih sedikit kebiasaan, jaga konsisten."},

"h-makamampu":{t:"h",ttl:"Beramal sesuai kemampuan",
ar:"مَهْ! عَلَيْكُمْ بِمَا تُطِيقُونَ، فَوَاللَّهِ لَا يَمَلُّ اللَّهُ حَتَّى تَمَلُّوا. وَكَانَ أَحَبَّ الدِّينِ إِلَيْهِ مَا دَاوَمَ عَلَيْهِ صَاحِبُهُ",
tr:"\"Tahanlah! Lakukanlah amal sesuai kemampuan kalian, karena demi Allah, Allah tidak akan bosan (memberi pahala) hingga kalian sendiri yang bosan.\" Dan agama (amalan) yang paling beliau cintai adalah yang dijaga terus-menerus oleh pelakunya. (dari Aisyah)",
takhrij:"HR Bukhari no. 43; juga Muslim no. 785.",
grade:"Sahih.",
sabab:"Asbabul wurud termuat dalam hadis: seorang wanita (disebut al-Haula' binti Tuwait) dipuji karena salat malam tanpa tidur, lalu Nabi ﷺ menegur dengan sabda ini — moderasi, bukan memaksakan diri.",
syarah:"An-Nawawi: \"Allah tidak bosan hingga kalian bosan\" maknanya Allah tidak memutus pahala selama kalian tidak memutus amal; perintahnya mengambil yang sanggup dijaga.",
note:"Sandaran sikap \"cukup baik dan konsisten\" — bukan perfeksionisme yang rapuh."},

"h-yassiru":{t:"h",ttl:"Permudahlah, gembirakanlah",
ar:"يَسِّرُوا وَلَا تُعَسِّرُوا، وَبَشِّرُوا وَلَا تُنَفِّرُوا",
tr:"\"Permudahlah dan jangan kalian persulit; berilah kabar gembira dan jangan membuat (orang) lari.\" (dari Anas bin Malik)",
takhrij:"HR Bukhari no. 69 (Kitab al-'Ilm) dan no. 6125 (Kitab al-Adab); Muslim no. 1734.",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Arahan umum dakwah dan pengajaran; dalam riwayat Muslim pesan serupa dibekalkan kepada Mu'adz dan Abu Musa saat diutus ke Yaman.",
syarah:"Ibnu Hajar (Fath al-Bari): yang baru memulai hendaknya diperlakukan lembut dan bertahap (tadarruj), sebab kesulitan di awal dapat membuatnya lari, sedangkan kemudahan menumbuhkannya.",
note:"Pedagogi kenabian: lembut, menggembirakan, bertahap — payung scaffolding."},

"h-dinyusr":{t:"h",ttl:"Agama itu mudah",
ar:"إِنَّ الدِّينَ يُسْرٌ، وَلَنْ يُشَادَّ الدِّينَ أَحَدٌ إِلَّا غَلَبَهُ، فَسَدِّدُوا وَقَارِبُوا وَأَبْشِرُوا",
tr:"\"Sesungguhnya agama itu mudah. Tidaklah seseorang memberat-beratkan diri dalam agama kecuali ia akan dikalahkan (kewalahan). Maka bersikaplah lurus, mendekatlah (kepada yang benar), dan bergembiralah.\" (dari Abu Hurairah)",
takhrij:"HR Bukhari no. 39.",
grade:"Sahih.",
sabab:"Tidak ada asbabul wurud khusus yang sahih; konteks bab al-Bukhari: agama yang dicintai adalah yang lurus lagi lapang (al-hanifiyyah as-samhah).",
syarah:"Ibnu Hajar: larangan ekstrem yang membuat putus amal; ambillah kesungguhan yang dapat dilanggengkan. \"Saddidu wa qaribu\": tepatlah, dan bila tak mampu sempurna, mendekatlah.",
note:"Penawar perfeksionisme pengasuhan: jalan tengah yang lestari."},

"h-tahnik":{t:"h",ttl:"Tahnik dan doa keberkahan",
ar:"وُلِدَ لِي غُلَامٌ، فَأَتَيْتُ بِهِ النَّبِيَّ ﷺ فَسَمَّاهُ إِبْرَاهِيمَ، فَحَنَّكَهُ بِتَمْرَةٍ، وَدَعَا لَهُ بِالْبَرَكَةِ، وَدَفَعَهُ إِلَيَّ",
tr:"Abu Musa berkata: \"Lahir anak laki-lakiku, lalu aku membawanya kepada Nabi ﷺ. Beliau menamainya Ibrahim, men-tahniknya dengan kurma, mendoakan keberkahan untuknya, lalu menyerahkannya kembali kepadaku.\"",
takhrij:"HR Bukhari no. 5467 dan Muslim no. 2145; senada hadis Asma' binti Abu Bakr tentang Abdullah bin az-Zubair (Bukhari no. 5469; Muslim no. 2146) dan hadis Anas tentang putra Abu Thalhah (Bukhari no. 5470; Muslim no. 2144).",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Para sahabat biasa membawa bayi yang baru lahir kepada Nabi ﷺ untuk didoakan; tahnik dengan kurma dan doa keberkahan adalah praktik beliau yang berulang.",
syarah:"An-Nawawi (Syarh Muslim): para ulama sepakat sunnahnya men-tahnik bayi dengan kurma saat lahir; bila tidak ada kurma, dengan yang manis lainnya. Ibn al-Qayyim menghimpun adab-adab ini dalam Tuhfat al-Maudud.",
note:"Adab menyambut yang paling kukuh sanadnya: tahnik + doa + nama yang baik."},

"h-azan-bayi":{t:"h",ttl:"Azan di telinga bayi — riwayat yang diperselisihkan",
ar:"رَأَيْتُ رَسُولَ اللَّهِ ﷺ أَذَّنَ فِي أُذُنِ الْحَسَنِ بْنِ عَلِيٍّ حِينَ وَلَدَتْهُ فَاطِمَةُ بِالصَّلَاةِ",
tr:"Abu Rafi' berkata: \"Aku melihat Rasulullah ﷺ mengumandangkan azan — seperti azan salat — di telinga al-Hasan bin Ali ketika Fathimah melahirkannya.\"",
takhrij:"HR Abu Dawud no. 5105; Tirmidzi no. 1514; Ahmad (Musnad 6/9); Abdurrazzaq (Mushannaf no. 7986); al-Hakim (Mustadrak 3/179).",
grade:"DIPERSELISIHKAN. Tirmidzi menilai hasan sahih dan al-Hakim menyahihkan sanadnya; namun pada sanadnya ada 'Ashim bin 'Ubaidillah yang dilemahkan banyak kritikus — sehingga Ibnu Hibban, al-Baihaqi, al-Mundziri, adz-Dzahabi, hingga al-Albani menilainya dha'if. Riwayat-riwayat penguatnya dinilai sangat lemah, dan riwayat IQAMAH di telinga kiri tergolong palsu (mawdu') menurut para pemeriksa hadis, termasuk al-Albani dalam Silsilah adh-Dha'ifah.",
sabab:"Konteks riwayatnya adalah kelahiran al-Hasan bin Ali.",
syarah:"Peta pendapat ulama: (1) Mazhab Syafi'i dan Hanbali menganjurkan azan di telinga kanan bayi (sebagian menambah iqamah di kiri), berpegang pada riwayat ini — termasuk Ibnu Taimiyyah (al-Kalim ath-Thayyib) dan Ibn al-Qayyim (Tuhfat al-Maudud) yang membuatkan bab khusus, serta ulama kontemporer seperti Bin Baz. (2) Imam Malik tidak menyukainya, dan ulama yang menilai hadisnya dha'if — seperti al-Albani dan Ibnu 'Utsaimin — berpendapat amalan ini tidak disyariatkan karena tidak ada dalil yang sahih. Keduanya pendapat ulama mu'tabar; modul ini tidak menyajikannya sebagai sunnah pasti, dan iqamah jelas ditinggalkan karena riwayatnya palsu.",
note:"Contoh nyata kejujuran derajat: yang kuat diamalkan, yang diperselisihkan dipetakan, yang palsu ditinggalkan."},

"h-rahmah-cium":{t:"h",ttl:"Nabi mencium anak; rahmah yang tercabut",
ar:"جَاءَ أَعْرَابِيٌّ إِلَى النَّبِيِّ ﷺ فَقَالَ: تُقَبِّلُونَ الصِّبْيَانَ؟ فَمَا نُقَبِّلُهُمْ. فَقَالَ النَّبِيُّ ﷺ: أَوَأَمْلِكُ لَكَ أَنْ نَزَعَ اللَّهُ مِنْ قَلْبِكَ الرَّحْمَةَ؟",
tr:"Seorang Arab badui datang kepada Nabi ﷺ lalu berkata, \"Kalian mencium anak-anak? Kami tidak pernah mencium mereka.\" Maka Nabi ﷺ bersabda, \"Apa dayaku bila Allah telah mencabut rahmat (kasih sayang) dari hatimu?\" (dari Aisyah)",
takhrij:"HR Bukhari no. 5998 dan Muslim no. 2317. Senada: hadis al-Aqra' bin Habis yang heran Nabi mencium al-Hasan, lalu beliau bersabda \"siapa tidak menyayangi, tidak disayangi\" (Bukhari no. 5997; Muslim no. 2318).",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Asbabul wurud termuat dalam hadis: keheranan badui atas kebiasaan Nabi mencium anak-anak.",
syarah:"Ibnu Hajar (Fath al-Bari): mencium anak karena kasih adalah bagian dari rahmah yang dipuji; kerasnya hati terhadap anak adalah kekurangan, bukan kejantanan.",
note:"Kehangatan fisik kepada anak adalah sunnah, bukan kemanjaan."},

"h-laysa-minna":{t:"h",ttl:"Bukan golongan kami yang tak menyayangi yang kecil",
ar:"لَيْسَ مِنَّا مَنْ لَمْ يَرْحَمْ صَغِيرَنَا، وَيَعْرِفْ شَرَفَ كَبِيرِنَا",
tr:"\"Bukan termasuk golongan kami orang yang tidak menyayangi yang kecil di antara kami dan tidak mengenal kehormatan orang besar (tua) di antara kami.\" (dari Abdullah bin 'Amr)",
takhrij:"HR Tirmidzi no. 1919 (lafal lain no. 1920: \"…dan tidak menghormati yang besar\"); Abu Dawud no. 4943; Ahmad.",
grade:"Sahih — dinilai sahih oleh al-Albani (Shahih at-Tirmidzi; Shahih al-Jami').",
sabab:"Tidak ada asbabul wurud khusus yang sahih.",
syarah:"Al-Mubarakfuri (Tuhfat al-Ahwadzi): \"laysa minna\" adalah ungkapan keras yang menunjukkan bahwa kasih kepada anak dan hormat kepada yang tua termasuk jalan kaum muslimin yang tak boleh ditinggalkan.",
note:"Rahmah kepada anak bukan pilihan gaya pengasuhan — ia identitas umat ini."},

"h-la-taghdab":{t:"h",ttl:"Jangan marah",
ar:"أَنَّ رَجُلًا قَالَ لِلنَّبِيِّ ﷺ: أَوْصِنِي. قَالَ: لَا تَغْضَبْ. فَرَدَّدَ مِرَارًا، قَالَ: لَا تَغْضَبْ",
tr:"Seorang lelaki berkata kepada Nabi ﷺ, \"Berilah aku wasiat.\" Beliau bersabda, \"Jangan marah.\" Orang itu mengulang berkali-kali, dan beliau (tetap) bersabda, \"Jangan marah.\" (dari Abu Hurairah)",
takhrij:"HR Bukhari no. 6116; termuat dalam al-Arba'in an-Nawawiyyah no. 16.",
grade:"Sahih.",
sabab:"Termuat dalam hadis: permintaan wasiat singkat dari seorang sahabat.",
syarah:"Ibnu Rajab: maknanya jangan turuti dorongan marah, dan latihlah akhlak yang mencabut akar kemarahan; bukan meniadakan emosi, melainkan menguasainya.",
note:"Ko-regulasi dimulai dari regulasi diri orang tua."},

"h-quwwah":{t:"h",ttl:"Orang kuat: yang menguasai diri saat marah",
ar:"لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ، إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ",
tr:"\"Orang kuat bukanlah yang menang bergulat; orang kuat hanyalah yang menguasai dirinya ketika marah.\" (dari Abu Hurairah)",
takhrij:"HR Bukhari no. 6114 dan Muslim no. 2609.",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Tidak ada asbabul wurud khusus yang sahih.",
syarah:"An-Nawawi: hadis ini memindahkan ukuran kekuatan dari fisik kepada pengendalian jiwa — itulah kekuatan yang terpuji.",
note:"Definisi kekuatan yang diajarkan kepada diri sebelum kepada anak."},

"h-rifq":{t:"h",ttl:"Allah mencintai kelembutan",
ar:"يَا عَائِشَةُ، إِنَّ اللَّهَ رَفِيقٌ يُحِبُّ الرِّفْقَ فِي الْأَمْرِ كُلِّهِ",
tr:"\"Wahai Aisyah, sesungguhnya Allah Mahalembut dan mencintai kelembutan dalam segala urusan.\" (dari Aisyah)",
takhrij:"HR Bukhari no. 6024 dan Muslim no. 2165. Senada (Muslim no. 2593): \"…Dia memberi pada kelembutan apa yang tidak Dia beri pada kekerasan\"; dan (Muslim no. 2594): \"Tidaklah kelembutan ada pada sesuatu kecuali menghiasinya, dan tidaklah dicabut dari sesuatu kecuali memperburuknya.\"",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Asbabul wurud termuat dalam hadis: sekelompok Yahudi memberi salam dengan pelesetan \"as-samu 'alaikum\" (kebinasaan atasmu); Aisyah membalas keras, lalu Nabi ﷺ menegurnya dengan sabda ini.",
syarah:"Ibnu Hajar: kelembutan menjadi sebab tercapainya tujuan yang tidak dicapai kekerasan; teguran kepada Aisyah menunjukkan rifq dituntut bahkan saat kita di pihak yang benar.",
note:"Rifq adalah inti ko-regulasi dan koreksi tanpa mempermalukan."},

"h-mukmin-kuat":{t:"h",ttl:"Mukmin yang kuat",
ar:"الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ، وَفِي كُلٍّ خَيْرٌ. احْرِصْ عَلَى مَا يَنْفَعُكَ وَاسْتَعِنْ بِاللَّهِ وَلَا تَعْجِزْ",
tr:"\"Mukmin yang kuat lebih baik dan lebih dicintai Allah daripada mukmin yang lemah, dan pada masing-masing ada kebaikan. Bersemangatlah atas apa yang bermanfaat bagimu, mohonlah pertolongan kepada Allah, dan jangan merasa lemah.\" (dari Abu Hurairah)",
takhrij:"HR Muslim no. 2664; Ibnu Majah no. 79.",
grade:"Sahih.",
sabab:"Tidak ada asbabul wurud khusus yang sahih.",
syarah:"An-Nawawi (Syarh Muslim): kekuatan yang dimaksud terutama keteguhan jiwa dalam urusan akhirat; para ulama juga memetik isyarat keutamaan badan yang sehat dan mampu — selama menjadi bekal ketaatan.",
note:"Mengembangkan gerak dan kebugaran anak = merawat amanah tubuh."},

"h-dolls-aisyah":{t:"h",ttl:"Aisyah bermain boneka di hadapan Nabi",
ar:"كُنْتُ أَلْعَبُ بِالْبَنَاتِ عِنْدَ النَّبِيِّ ﷺ، وَكَانَ لِي صَوَاحِبُ يَلْعَبْنَ مَعِي، فَكَانَ رَسُولُ اللَّهِ ﷺ إِذَا دَخَلَ يَتَقَمَّعْنَ مِنْهُ، فَيُسَرِّبُهُنَّ إِلَيَّ فَيَلْعَبْنَ مَعِي",
tr:"Aisyah berkata: \"Aku biasa bermain boneka (al-banat) di sisi Nabi ﷺ, dan aku punya teman-teman yang bermain bersamaku. Bila Rasulullah ﷺ masuk, mereka bersembunyi dari beliau — maka beliau justru mengirim mereka kembali kepadaku agar bermain bersamaku.\"",
takhrij:"HR Bukhari no. 6130; Muslim no. 2440.",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Termuat dalam hadis: kebiasaan Aisyah kecil bermain bersama teman-temannya di rumah Nabi ﷺ.",
syarah:"An-Nawawi, Ibnu Battal, dan Ibnu Hajar menjadikan hadis ini dalil bolehnya mainan anak. Peta fiqh tashwir pada mainan: banyak fuqaha MENGECUALIKAN mainan anak dari larangan umum gambar/patung (rukhshah demi pendidikan dan kasih, sebagaimana dinukil Ibnu Hajar dalam Fath al-Bari); sebagian lain mensyaratkan bentuknya tidak utuh/rinci. Keluarga memilih dengan ilmu di antara pendapat-pendapat mu'tabar ini.",
note:"Nabi bukan sekadar membolehkan — beliau memfasilitasi anak bermain."},

"h-eid-duff":{t:"h",ttl:"Dua gadis bernyanyi pada hari raya",
ar:"دَخَلَ أَبُو بَكْرٍ وَعِنْدِي جَارِيَتَانِ مِنْ جَوَارِي الْأَنْصَارِ تُغَنِّيَانِ بِمَا تَقَاوَلَتِ الْأَنْصَارُ يَوْمَ بُعَاثَ... فَقَالَ أَبُو بَكْرٍ: أَمَزَامِيرُ الشَّيْطَانِ فِي بَيْتِ رَسُولِ اللَّهِ ﷺ؟ فَقَالَ رَسُولُ اللَّهِ ﷺ: يَا أَبَا بَكْرٍ، إِنَّ لِكُلِّ قَوْمٍ عِيدًا، وَهَذَا عِيدُنَا",
tr:"Aisyah berkata: Abu Bakar masuk saat di sisiku ada dua gadis kecil Anshar yang bernyanyi dengan syair (hari) Bu'ats… Abu Bakar berkata, \"Seruling setan di rumah Rasulullah?\" Maka Rasulullah ﷺ bersabda, \"Wahai Abu Bakar, setiap kaum punya hari raya, dan inilah hari raya kita.\" (sebagian riwayat menyebut keduanya menabuh duff)",
takhrij:"HR Bukhari no. 949 dan 952; Muslim no. 892.",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Termuat dalam hadis: hari raya 'Id di rumah Aisyah; teguran Abu Bakar dan jawaban Nabi ﷺ.",
syarah:"Ibnu Hajar: hadis ini dalil keluasan pada hari gembira — nyanyian gadis kecil dan duff yang mubah diberi tempat. Para ulama membedakannya dari nyanyian yang diiringi kemungkaran.",
note:"Lagu gembira dan duff punya tempat — terutama pada momen bahagia."},

"h-maazif":{t:"h",ttl:"Riwayat al-ma'azif — poros khilaf alat musik",
ar:"لَيَكُونَنَّ مِنْ أُمَّتِي أَقْوَامٌ يَسْتَحِلُّونَ الْحِرَ وَالْحَرِيرَ وَالْخَمْرَ وَالْمَعَازِفَ",
tr:"\"Sungguh akan ada di antara umatku kaum-kaum yang menghalalkan zina, sutra, khamar, dan alat-alat musik (al-ma'azif)…\" (dari Abu Malik al-Asy'ari)",
takhrij:"HR Bukhari no. 5590 (riwayat mu'allaq dengan sighat jazm; disambungkan sanadnya oleh Abu Dawud no. 4039, al-Baihaqi, dan lainnya).",
grade:"Derajat KEBERSAMBUNGANNYA diperselisihkan: jumhur ahli hadis — termasuk Ibnu Hajar — menilainya sahih dan bersambung; Ibnu Hazm menilainya munqathi' (terputus) sehingga tidak menjadikannya hujah.",
sabab:"Tidak ada asbabul wurud khusus; konteksnya peringatan tentang kaum yang menghalalkan hal-hal tersebut.",
syarah:"Peta khilaf hukum alat musik: (1) JUMHUR empat mazhab cenderung melarang alat musik selain duff, berdalil antara lain riwayat ini dan yang senada. (2) IBNU HAZM — dan yang searah dengannya dari sebagian ulama dahulu maupun kontemporer — menilai riwayat-riwayat pelarangan tidak sahih atau tidak tegas, sehingga kembali ke hukum asal mubah selama tidak melalaikan dari kewajiban. Yang DISEPAKATI lebih luas: suara manusia, senandung, nasyid tanpa kemungkaran, duff pada momen gembira, dan keindahan tilawah. Modul ini menyajikan peta ini apa adanya tanpa berfatwa — keluarga memilih dengan ilmu.",
note:"Ikhtilaf besar yang disajikan adil — kedua kubu adalah ulama mu'tabar."},

"h-attaghanni":{t:"h",ttl:"Allah mendengarkan tilawah yang diperindah",
ar:"مَا أَذِنَ اللَّهُ لِشَيْءٍ مَا أَذِنَ لِنَبِيٍّ حَسَنِ الصَّوْتِ يَتَغَنَّى بِالْقُرْآنِ يَجْهَرُ بِهِ",
tr:"\"Allah tidak mendengarkan (dengan penuh perkenan) sesuatu sebagaimana Dia mendengarkan seorang nabi yang bagus suaranya melagukan Al-Qur'an dengan mengeraskannya.\" (dari Abu Hurairah)",
takhrij:"HR Bukhari no. 5023–5024; Muslim no. 792.",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Tidak ada asbabul wurud khusus yang sahih.",
syarah:"Para ulama: \"yataghanna\" bermakna memperindah dan melagukan bacaan (sebagian menambahkan makna merasa cukup dengannya). Memperindah suara untuk Al-Qur'an adalah ibadah yang dicintai.",
note:"Irama terindah yang dihadiahkan ke telinga anak: tilawah yang tartil."},

"h-anjing":{t:"h",ttl:"Pahala pada setiap makhluk bernyawa",
ar:"بَيْنَمَا رَجُلٌ يَمْشِي فَاشْتَدَّ عَلَيْهِ الْعَطَشُ، فَنَزَلَ بِئْرًا فَشَرِبَ مِنْهَا، ثُمَّ خَرَجَ فَإِذَا هُوَ بِكَلْبٍ يَلْهَثُ يَأْكُلُ الثَّرَى مِنَ الْعَطَشِ... فَمَلَأَ خُفَّهُ ثُمَّ أَمْسَكَهُ بِفِيهِ، ثُمَّ رَقِيَ فَسَقَى الْكَلْبَ، فَشَكَرَ اللَّهُ لَهُ فَغَفَرَ لَهُ. قَالُوا: يَا رَسُولَ اللَّهِ، وَإِنَّ لَنَا فِي الْبَهَائِمِ أَجْرًا؟ قَالَ: فِي كُلِّ كَبِدٍ رَطْبَةٍ أَجْرٌ",
tr:"\"Seorang lelaki berjalan lalu sangat kehausan; ia turun ke sumur dan minum. Saat keluar, ia mendapati seekor anjing menjulurkan lidah menjilati tanah basah karena kehausan… maka ia memenuhi sepatunya (dengan air), menggigitnya, naik, lalu memberi minum anjing itu. Allah pun berterima kasih kepadanya dan mengampuninya.\" Para sahabat bertanya, \"Wahai Rasulullah, apakah pada (menolong) hewan ada pahala bagi kami?\" Beliau menjawab, \"Pada setiap (makhluk yang punya) hati yang basah (bernyawa) ada pahala.\"",
takhrij:"HR Bukhari no. 2466 dan no. 6009; Muslim no. 2244. Riwayat senada: seorang wanita pezina Bani Israil diampuni karena memberi minum anjing (Bukhari no. 3321; Muslim no. 2245).",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Asbabul wurud kalimat \"fi kulli kabidin rathbatin ajr\" termuat dalam hadis: pertanyaan sahabat tentang pahala menolong hewan.",
syarah:"Ibnu Hajar: hadis ini dasar bahwa berbuat ihsan kepada hewan mendatangkan pahala dan ampunan — sekecil apa pun makhluknya.",
note:"Mengajari anak lembut pada semut, kucing, dan burung adalah menanam rahmah."},

"h-kucing":{t:"h",ttl:"Wanita yang menyiksa kucing",
ar:"عُذِّبَتِ امْرَأَةٌ فِي هِرَّةٍ سَجَنَتْهَا حَتَّى مَاتَتْ، فَدَخَلَتْ فِيهَا النَّارَ، لَا هِيَ أَطْعَمَتْهَا وَلَا سَقَتْهَا إِذْ حَبَسَتْهَا، وَلَا هِيَ تَرَكَتْهَا تَأْكُلُ مِنْ خَشَاشِ الْأَرْضِ",
tr:"\"Seorang wanita diazab karena seekor kucing yang ia kurung sampai mati, sehingga ia masuk neraka karenanya: ia tidak memberinya makan dan minum ketika mengurungnya, dan tidak pula melepasnya agar makan dari serangga tanah.\" (dari Ibnu Umar)",
takhrij:"HR Bukhari no. 3318; Muslim no. 2242.",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Tidak ada asbabul wurud khusus; disampaikan sebagai peringatan tentang kekejaman pada hewan.",
syarah:"An-Nawawi: hadis ini dalil haramnya menyiksa hewan dan bahwa dosa kepada makhluk bisa menjadi sebab azab.",
note:"Dua sisi rahmah: menolong berpahala, menzalimi berdosa — diajarkan lewat contoh lembut, tanpa menakut-nakuti anak."},

"h-umar-abi-salamah":{t:"h",ttl:"Mengajar adab makan di momen nyata",
ar:"كُنْتُ غُلَامًا فِي حَجْرِ رَسُولِ اللَّهِ ﷺ، وَكَانَتْ يَدِي تَطِيشُ فِي الصَّحْفَةِ، فَقَالَ لِي رَسُولُ اللَّهِ ﷺ: يَا غُلَامُ، سَمِّ اللَّهَ، وَكُلْ بِيَمِينِكَ، وَكُلْ مِمَّا يَلِيكَ",
tr:"Umar bin Abi Salamah berkata: \"Aku adalah anak kecil dalam asuhan Rasulullah ﷺ, dan tanganku berkeliling ke sana-sini di nampan. Maka Rasulullah ﷺ bersabda kepadaku: 'Wahai anak, sebutlah nama Allah, makanlah dengan tangan kananmu, dan makanlah dari yang ada di dekatmu.'\"",
takhrij:"HR Bukhari no. 5376 dan Muslim no. 2022.",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Asbabul wurud termuat dalam hadis: tangan kecil Umar yang berkeliling di nampan makanan.",
syarah:"Ibnu Hajar: hadis ini model pengajaran anak — singkat, di momen nyata, dengan panggilan lembut, tanpa mempermalukan. Umar berkata: \"maka begitulah cara makanku setelahnya\" — pengajaran yang membekas seumur hidup.",
note:"Tiga kalimat di momen nyata mengalahkan ceramah panjang."},

"h-akhlaq-misi":{t:"h",ttl:"Diutus menyempurnakan akhlak",
ar:"إِنَّمَا بُعِثْتُ لِأُتَمِّمَ صَالِحَ الْأَخْلَاقِ",
tr:"\"Sesungguhnya aku diutus hanyalah untuk menyempurnakan akhlak yang baik.\" (dari Abu Hurairah; lafal lain: makarimal akhlaq — kemuliaan akhlak)",
takhrij:"HR Ahmad no. 8952; al-Bukhari dalam al-Adab al-Mufrad no. 273; al-Hakim; serta mursal Malik dalam al-Muwaththa'.",
grade:"Sahih — dinilai sahih oleh al-Albani (Shahih al-Adab al-Mufrad; ash-Shahihah no. 45) dan oleh Syu'aib al-Arna'uth dalam tahqiq Musnad Ahmad.",
sabab:"Tidak ada asbabul wurud khusus yang sahih.",
syarah:"Ibnu Abdil Barr (at-Tamhid): kebaikan, agama, keutamaan, muruah, ihsan, dan keadilan — semuanya tercakup dalam akhlak yang beliau diutus untuk menyempurnakannya. Akhlak bukan pelengkap; ia inti risalah.",
note:"Maka 'kecerdasan hati' diletakkan di atas semua ranah lain dalam kurikulum ini."},

"h-adab-janji":{t:"a",ttl:"Menepati janji kepada anak (atsar Ibnu Mas'ud)",
ar:"لَا يَصْلُحُ الْكَذِبُ فِي جِدٍّ وَلَا هَزْلٍ، وَلَا أَنْ يَعِدَ أَحَدُكُمْ صَبِيَّهُ ثُمَّ لَا يُنْجِزَ لَهُ",
tr:"Ibnu Mas'ud berkata: \"Dusta itu tidak pantas, baik sungguh-sungguh maupun bercanda; dan tidak pantas seseorang menjanjikan sesuatu kepada anaknya lalu tidak menepatinya.\"",
takhrij:"Al-Adab al-Mufrad no. 387 (mauquf dari Ibnu Mas'ud). Penguat marfu': hadis Abdullah bin 'Amir — ibunya memanggilnya \"kemarilah, kuberi sesuatu\", lalu Nabi ﷺ bersabda: \"Seandainya engkau tidak memberinya sesuatu, niscaya dicatat atasmu satu dusta\" (HR Abu Dawud no. 4991 — hasan menurut al-Albani).",
grade:"Mauquf sahih (al-Albani, Shahih al-Adab al-Mufrad); maknanya dikuatkan riwayat marfu' yang hasan.",
sabab:"—",
syarah:"Para ulama: janji kepada anak adalah utang adab; mengingkarinya mengajari anak bahwa kata-kata boleh tidak bermakna — lawan dari pendidikan kejujuran.",
note:"Adab pertama orang tua: jangan jadikan janji kosong sebagai alat menenangkan anak."},

"h-fitrah":{t:"h",ttl:"Setiap anak lahir di atas fitrah",
ar:"مَا مِنْ مَوْلُودٍ إِلَّا يُولَدُ عَلَى الْفِطْرَةِ، فَأَبَوَاهُ يُهَوِّدَانِهِ أَوْ يُنَصِّرَانِهِ أَوْ يُمَجِّسَانِهِ",
tr:"\"Tidak ada satu pun anak yang lahir kecuali ia dilahirkan di atas fitrah; lalu kedua orang tuanyalah yang menjadikannya Yahudi, Nasrani, atau Majusi.\" (dari Abu Hurairah)",
takhrij:"HR Bukhari no. 1358–1359 (juga no. 1385); Muslim no. 2658.",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Tidak ada asbabul wurud khusus; Abu Hurairah lalu membaca ayat fitrah (Ar-Rum 30:30).",
syarah:"Ibnu Hajar dan an-Nawawi: fitrah adalah kecenderungan asal kepada tauhid dan kebaikan; peran terbesar dalam menjaganya atau membelokkannya ada pada kedua orang tua. Anak datang membawa kebaikan asal — tugas kita merawat, bukan menciptakan.",
note:"Mengasuh = menjaga fitrah: optimis pada anak, serius pada teladan."},

"h-rain":{t:"h",ttl:"Setiap kalian adalah pemimpin",
ar:"كُلُّكُمْ رَاعٍ وَكُلُّكُمْ مَسْئُولٌ عَنْ رَعِيَّتِهِ، الْإِمَامُ رَاعٍ وَمَسْئُولٌ عَنْ رَعِيَّتِهِ، وَالرَّجُلُ رَاعٍ فِي أَهْلِهِ وَهُوَ مَسْئُولٌ عَنْ رَعِيَّتِهِ، وَالْمَرْأَةُ رَاعِيَةٌ فِي بَيْتِ زَوْجِهَا وَمَسْئُولَةٌ عَنْ رَعِيَّتِهَا",
tr:"\"Setiap kalian adalah pemimpin (penggembala) dan setiap kalian bertanggung jawab atas yang dipimpinnya: imam adalah pemimpin dan bertanggung jawab atas rakyatnya; lelaki adalah pemimpin dalam keluarganya dan bertanggung jawab atas yang dipimpinnya; perempuan adalah pemimpin di rumah suaminya dan bertanggung jawab atas yang dipimpinnya…\" (dari Ibnu Umar)",
takhrij:"HR Bukhari no. 893 (juga no. 2409, 7138); Muslim no. 1829.",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Tidak ada asbabul wurud khusus yang sahih.",
syarah:"Ibnu Hajar: ra'in adalah penjaga yang diamanahi kemaslahatan apa yang diasuhnya — maka ayah DAN ibu sama-sama memikul amanah pengasuhan, masing-masing pada perannya, dan keduanya akan ditanya.",
note:"Pengasuhan bukan tugas satu orang dibantu yang lain — keduanya penanggung jawab."},

"h-jasad-haq":{t:"h",ttl:"Tubuh, mata, dan pasanganmu punya hak",
ar:"فَإِنَّ لِجَسَدِكَ عَلَيْكَ حَقًّا، وَإِنَّ لِعَيْنِكَ عَلَيْكَ حَقًّا، وَإِنَّ لِزَوْجِكَ عَلَيْكَ حَقًّا",
tr:"\"…Sesungguhnya tubuhmu punya hak atasmu, matamu punya hak atasmu, dan pasanganmu punya hak atasmu…\" (kepada Abdullah bin 'Amr yang berpuasa dan salat malam tanpa henti)",
takhrij:"HR Bukhari no. 5199 (Kitab an-Nikah); kisah lengkapnya juga pada Bukhari no. 1975 dan Muslim no. 1159.",
grade:"Sahih.",
sabab:"Asbabul wurud termuat dalam hadis: Abdullah bin 'Amr bertekad puasa setiap hari dan salat sepanjang malam; Nabi ﷺ meluruskannya kepada keseimbangan.",
syarah:"Ibnu Hajar: hadis ini pokok dalam keseimbangan hak — ibadah tidak boleh menzalimi badan dan keluarga; istirahat adalah menunaikan hak, bukan kelalaian.",
note:"Merawat diri orang tua bukan egois — ia penunaian hak."},

"h-salman":{t:"h",ttl:"Nasihat Salman: tunaikan setiap hak",
ar:"إِنَّ لِرَبِّكَ عَلَيْكَ حَقًّا، وَلِنَفْسِكَ عَلَيْكَ حَقًّا، وَلِأَهْلِكَ عَلَيْكَ حَقًّا، فَأَعْطِ كُلَّ ذِي حَقٍّ حَقَّهُ. فَأَتَى النَّبِيَّ ﷺ فَذَكَرَ ذَلِكَ لَهُ، فَقَالَ النَّبِيُّ ﷺ: صَدَقَ سَلْمَانُ",
tr:"Salman berkata (kepada Abu Darda yang berlebihan ibadah): \"Sesungguhnya Tuhanmu punya hak atasmu, dirimu punya hak atasmu, dan keluargamu punya hak atasmu — maka berikanlah kepada setiap pemilik hak haknya.\" Lalu hal itu disampaikan kepada Nabi ﷺ, dan beliau bersabda: \"Benarlah Salman.\"",
takhrij:"HR Bukhari no. 1968.",
grade:"Sahih.",
sabab:"Asbabul wurud termuat dalam hadis: Salman dipersaudarakan dengan Abu Darda, lalu mendapati ia (dan istrinya terabaikan karena) ibadah tanpa henti.",
syarah:"Ibnu Hajar: pengakuan Nabi (taqrir) menjadikan kaidah ini syariat — keseimbangan antara ibadah, diri, dan keluarga adalah perintah, bukan kelonggaran.",
note:"Dasar 'wellbeing' orang tua dalam bahasa wahyu: setiap hak ditunaikan."},

"h-unzhuru":{t:"h",ttl:"Lihatlah kepada yang di bawahmu",
ar:"انْظُرُوا إِلَى مَنْ أَسْفَلَ مِنْكُمْ، وَلَا تَنْظُرُوا إِلَى مَنْ هُوَ فَوْقَكُمْ، فَهُوَ أَجْدَرُ أَنْ لَا تَزْدَرُوا نِعْمَةَ اللَّهِ عَلَيْكُمْ",
tr:"\"Lihatlah kepada orang yang di bawah kalian (dalam urusan dunia), dan jangan melihat kepada yang di atas kalian; itu lebih layak agar kalian tidak meremehkan nikmat Allah atas kalian.\" (dari Abu Hurairah)",
takhrij:"HR Muslim no. 2963; Bukhari no. 6490 dengan lafal senada.",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Tidak ada asbabul wurud khusus yang sahih.",
syarah:"An-Nawawi: ini obat hati dari hasad dan keluh — melihat ke bawah dalam urusan dunia menumbuhkan syukur. Para ulama menambah: dalam urusan agama, lihatlah ke atas.",
note:"Penawar budaya banding-membandingkan pengasuhan di media sosial."},

"h-kadzib-nabi":{t:"h",ttl:"Ancaman berdusta atas nama Nabi",
ar:"مَنْ كَذَبَ عَلَيَّ مُتَعَمِّدًا فَلْيَتَبَوَّأْ مَقْعَدَهُ مِنَ النَّارِ",
tr:"\"Barangsiapa sengaja berdusta atas namaku, hendaklah ia menyiapkan tempat duduknya di neraka.\"",
takhrij:"HR Bukhari no. 110 (dan lainnya); Muslim no. 3 (Muqaddimah) — diriwayatkan dari banyak sahabat hingga mencapai derajat mutawatir.",
grade:"Sahih mutawatir.",
sabab:"Tidak ada asbabul wurud tunggal; konteks umumnya peringatan menjaga kemurnian sabda Nabi ﷺ.",
syarah:"Inilah akar lahirnya ilmu hadis: umat membangun sistem verifikasi sanad agar tidak menisbatkan kepada Nabi apa yang tidak beliau ucapkan. Menyebarkan riwayat tanpa memeriksa termasuk yang diperingatkan.",
note:"Sebelum meneruskan 'hadis' pengasuhan yang viral: periksa dulu."},

"h-muawiyah":{t:"h",ttl:"Sebaik-baik pengajar (kisah Mu'awiyah bin al-Hakam)",
ar:"فَبِأَبِي هُوَ وَأُمِّي، مَا رَأَيْتُ مُعَلِّمًا قَبْلَهُ وَلَا بَعْدَهُ أَحْسَنَ تَعْلِيمًا مِنْهُ، فَوَاللَّهِ مَا كَهَرَنِي وَلَا ضَرَبَنِي وَلَا شَتَمَنِي",
tr:"Mu'awiyah bin al-Hakam berkata (setelah ia berbicara di tengah salat dan Nabi menjelaskannya dengan tenang seusai salat): \"Demi ayah dan ibuku, aku tidak pernah melihat seorang pengajar pun sebelum maupun sesudah beliau yang lebih baik pengajarannya daripada beliau. Demi Allah, beliau tidak membentakku, tidak memukulku, dan tidak mencelaku.\"",
takhrij:"HR Muslim no. 537.",
grade:"Sahih.",
sabab:"Termuat dalam hadis: Mu'awiyah menjawab orang bersin dengan ucapan di tengah salat; seusai salat Nabi ﷺ hanya menjelaskan bahwa salat bukan tempat percakapan manusia.",
syarah:"An-Nawawi: hadis ini menghimpun keagungan akhlak Nabi dalam mengajar — kelembutan kepada yang tidak tahu, koreksi tanpa mempermalukan; teladan bagi pengajar dan orang tua.",
note:"Standar emas koreksi: jelas, tenang, tanpa bentakan dan tanpa mempermalukan."},

"h-rahimun":{t:"h",ttl:"Para penyayang disayangi Ar-Rahman",
ar:"الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ، ارْحَمُوا مَنْ فِي الْأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ",
tr:"\"Orang-orang yang penyayang akan disayangi oleh Ar-Rahman (Yang Maha Penyayang). Sayangilah siapa yang di bumi, niscaya Yang di langit menyayangi kalian.\" (dari Abdullah bin 'Amr)",
takhrij:"HR Abu Dawud no. 4941; Tirmidzi no. 1924 — Tirmidzi: hasan sahih.",
grade:"Sahih — dinilai sahih oleh al-Albani; dikenal sebagai hadis musalsal bil-awwaliyyah (hadis pertama yang lazim diriwayatkan guru kepada murid).",
sabab:"Tidak ada asbabul wurud khusus yang sahih.",
syarah:"Al-Mubarakfuri: rahmah yang dimaksud mencakup seluruh makhluk — manusia, anak-anak, dan hewan; balasannya rahmat dari Allah.",
note:"Membelai janin dan menyayangi anak adalah bagian dari budaya rahmah ini."},

"h-kalimah-sadaqah":{t:"h",ttl:"Perkataan yang baik adalah sedekah",
ar:"وَالْكَلِمَةُ الطَّيِّبَةُ صَدَقَةٌ",
tr:"\"…dan perkataan yang baik adalah sedekah…\" (bagian dari hadis tentang sedekah setiap ruas tubuh, dari Abu Hurairah)",
takhrij:"HR Bukhari no. 2989; Muslim no. 1009.",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Termuat dalam hadis panjang tentang sedekah harian setiap persendian manusia.",
syarah:"An-Nawawi: kata yang baik — dzikir, nasihat, sapaan lembut — bernilai sedekah; murah, mudah, dan bisa setiap saat.",
note:"Rumah yang penuh kata baik = rumah yang bersedekah sepanjang hari kepada anaknya."},

"h-aqiqah":{t:"h",ttl:"Aqiqah, penamaan, dan cukur rambut hari ketujuh",
ar:"كُلُّ غُلَامٍ مُرْتَهَنٌ بِعَقِيقَتِهِ، تُذْبَحُ عَنْهُ يَوْمَ سَابِعِهِ، وَيُحْلَقُ رَأْسُهُ، وَيُسَمَّى",
tr:"\"Setiap anak tergadai dengan aqiqahnya: disembelihkan untuknya pada hari ketujuhnya, dicukur rambutnya, dan diberi nama.\" (dari Samurah bin Jundub)",
takhrij:"HR Abu Dawud no. 2838; Tirmidzi no. 1522; an-Nasa'i no. 4220; Ibnu Majah no. 3165.",
grade:"Sahih — Tirmidzi: hasan sahih; disahihkan al-Albani.",
sabab:"Tidak ada asbabul wurud khusus yang sahih.",
syarah:"Ibn al-Qayyim (Tuhfat al-Maudud) merinci adab-adab ini; jumhur ulama: aqiqah sunnah muakkadah — dua kambing untuk anak laki-laki dan satu untuk perempuan menurut riwayat sahih lainnya.",
note:"Persiapan menyambut: rencanakan nama yang baik dan aqiqah sejak masa hamil."},

"h-irmi":{t:"h",ttl:"Kekuatan itu memanah (penguat sahih ketangkasan)",
ar:"أَلَا إِنَّ الْقُوَّةَ الرَّمْيُ، أَلَا إِنَّ الْقُوَّةَ الرَّمْيُ، أَلَا إِنَّ الْقُوَّةَ الرَّمْيُ",
tr:"\"Ketahuilah, sesungguhnya kekuatan itu adalah memanah\" — beliau ucapkan tiga kali. (dari 'Uqbah bin 'Amir, menafsirkan QS Al-Anfal 8:60)",
takhrij:"HR Muslim no. 1917. Senada: \"Memanahlah dan berkudalah…\" (Abu Dawud no. 2513).",
grade:"Sahih.",
sabab:"Disabdakan di atas mimbar saat membaca ayat \"wa a'iddu lahum mastatha'tum min quwwah\".",
syarah:"An-Nawawi: anjuran melatih ketangkasan yang bermanfaat. Inilah penyandaran yang BENAR bagi nilai melatih fisik anak — sedangkan ungkapan \"ajari anakmu berenang, memanah, dan berkuda\" adalah atsar Umar bin Khattab (lihat kartu atsar), bukan hadis Nabi.",
note:"Nilai ketangkasan fisik berdiri di atas dalil sahih — dengan penyandaran yang jujur."},

"a-umar-renang":{t:"a",ttl:"Atsar Umar: ajari anakmu berenang dan memanah",
ar:"عَلِّمُوا أَوْلَادَكُمُ السِّبَاحَةَ وَالرِّمَايَةَ",
tr:"\"Ajarilah anak-anak kalian berenang dan memanah\" (sebagian riwayat menambah: \"dan menunggang kuda\").",
takhrij:"Atsar Umar bin Khattab — diriwayatkan antara lain dalam Mushannaf Abdurrazzaq (surat Umar kepada penduduk Syam) dan al-Baihaqi.",
grade:"PERKATAAN UMAR (atsar/mauquf) — BUKAN hadis Nabi ﷺ. Versi yang dinisbatkan kepada Nabi sanadnya sangat lemah. Nilainya didukung dalil sahih lain (lihat kartu \"Kekuatan itu memanah\").",
sabab:"Konteks riwayat: arahan Umar sebagai khalifah kepada penduduk wilayah agar membekali anak-anak keterampilan fisik.",
syarah:"Inilah praktik literasi sumber: ungkapan yang baik tetap diamalkan nilainya, tetapi penyandarannya diluruskan — perkataan sahabat tidak dinaikkan menjadi sabda Nabi.",
note:"Koreksi penyandaran yang paling sering keliru di dunia parenting Islami."},

"a-ibnu-sirin":{t:"a",ttl:"Ilmu ini adalah agama (Ibnu Sirin)",
ar:"إِنَّ هَذَا الْعِلْمَ دِينٌ، فَانْظُرُوا عَمَّنْ تَأْخُذُونَ دِينَكُمْ",
tr:"Muhammad bin Sirin berkata: \"Sesungguhnya ilmu ini adalah agama, maka perhatikanlah dari siapa kalian mengambil agama kalian.\"",
takhrij:"Muqaddimah Sahih Muslim.",
grade:"Atsar tabi'in yang masyhur dan diterima.",
sabab:"Diucapkan di masa mulai munculnya fitnah dan pemalsuan riwayat — para ulama lalu menuntut sanad.",
syarah:"Imam Muslim menempatkannya di muqaddimah sebagai asas: memeriksa pembawa kabar adalah bagian dari menjaga agama.",
note:"Memilih sumber dan guru untuk anak adalah amanah, bukan formalitas."},

"a-ibnul-mubarak":{t:"a",ttl:"Isnad bagian dari agama (Ibnul Mubarak)",
ar:"الْإِسْنَادُ مِنَ الدِّينِ، وَلَوْلَا الْإِسْنَادُ لَقَالَ مَنْ شَاءَ مَا شَاءَ",
tr:"Abdullah bin al-Mubarak berkata: \"Isnad (rantai periwayatan) itu bagian dari agama; seandainya tanpa isnad, niscaya siapa pun berkata apa saja yang ia mau.\"",
takhrij:"Muqaddimah Sahih Muslim.",
grade:"Atsar masyhur dan diterima.",
sabab:"Diucapkan menanggapi maraknya riwayat tanpa sanad.",
syarah:"Inilah akar tradisi verifikasi Islam yang berusia berabad-abad: menimbang SIAPA yang menyampaikan, bukan sekadar APA yang tersebar — leluhur 'literasi sumber' modern.",
note:"Warisan metodologi yang kita teruskan ke anak: tanya \"dari mana?\""},

"k-ghazali-permata":{t:"k",ttl:"Al-Ghazali: hati anak bagai permata",
ar:"وَالصَّبِيُّ أَمَانَةٌ عِنْدَ وَالِدَيْهِ، وَقَلْبُهُ الطَّاهِرُ جَوْهَرَةٌ نَفِيسَةٌ سَاذَجَةٌ خَالِيَةٌ عَنْ كُلِّ نَقْشٍ وَصُورَةٍ، وَهُوَ قَابِلٌ لِكُلِّ مَا نُقِشَ، وَمَائِلٌ إِلَى كُلِّ مَا يُمَالُ بِهِ إِلَيْهِ",
tr:"\"Anak adalah amanah di sisi kedua orang tuanya. Hatinya yang suci adalah permata berharga yang masih polos, kosong dari setiap ukiran dan gambar; ia menerima apa pun yang diukirkan padanya, dan condong kepada apa pun yang ia dicondongkan kepadanya.\"",
takhrij:"Al-Ghazali, Ihya 'Ulumiddin — bagian Riyadhatus Shibyan (melatih anak-anak).",
grade:"Perkataan ulama (bukan dalil syar'i) — hikmah pendidikan dari imam yang mu'tabar.",
sabab:"—",
syarah:"Al-Ghazali melanjutkan: bila dibiasakan kebaikan dan diajarkan, ia tumbuh di atasnya dan berbahagialah ia serta kedua orang tuanya. Pembiasaan (ta'wid) sejak dini adalah kunci — ditanam lembut, bukan dipaksa.",
note:"Bingkai khazanah: amanah, fitrah yang dibentuk, dan kuasa pembiasaan."},

"k-ghazali-main":{t:"k",ttl:"Al-Ghazali: anak butuh bermain",
ar:"وَيَنْبَغِي أَنْ يُؤْذَنَ لَهُ بَعْدَ الِانْصِرَافِ مِنَ الْكُتَّابِ أَنْ يَلْعَبَ لَعِبًا جَمِيلًا يَسْتَرِيحُ إِلَيْهِ مِنْ تَعَبِ الْمَكْتَبِ... فَإِنَّ مَنْعَ الصَّبِيِّ مِنَ اللَّعِبِ وَإِرْهَاقَهُ إِلَى التَّعَلُّمِ دَائِمًا يُمِيتُ قَلْبَهُ وَيُبْطِلُ ذَكَاءَهُ",
tr:"\"Hendaknya anak diizinkan — sepulang dari tempat belajar — bermain dengan permainan yang baik untuk beristirahat dari penatnya belajar… karena melarang anak bermain dan terus memaksanya belajar akan mematikan hatinya dan menumpulkan kecerdasannya, serta membuat hidup terasa berat baginya.\"",
takhrij:"Al-Ghazali, Ihya 'Ulumiddin — Riyadhatus Shibyan.",
grade:"Perkataan ulama — hikmah pendidikan yang mu'tabar.",
sabab:"—",
syarah:"Sembilan abad sebelum sains bermain modern, al-Ghazali telah menempatkan bermain sebagai kebutuhan jiwa anak, bukan gangguan belajar.",
note:"Penopang khazanah bagi prinsip \"utamakan bermain, jangan 'menyekolahkan' balita\"."},

"k-tuhfat":{t:"k",ttl:"Ibn al-Qayyim: Tuhfat al-Maudud",
ar:"تُحْفَةُ الْمَوْدُودِ بِأَحْكَامِ الْمَوْلُودِ",
tr:"\"Tuhfat al-Maudud bi Ahkam al-Maulud\" — hadiah bagi anak tercinta: himpunan hukum-hukum seputar bayi yang baru lahir.",
takhrij:"Karya Ibn al-Qayyim al-Jauziyyah (w. 751 H), murid Ibnu Taimiyyah.",
grade:"Kitab rujukan mu'tabar dalam fiqh dan adab menyambut kelahiran.",
sabab:"—",
syarah:"Kitab ini menghimpun adab dan hukum menyambut bayi: tahnik, penamaan yang baik, aqiqah, mencukur rambut hari ketujuh — beserta diskusi dalil-dalilnya, termasuk membahas riwayat azan di telinga bayi (yang derajatnya diperselisihkan, lihat kartu tersendiri).",
note:"Rujukan klasik utama bagi modul Doa, Niat, dan Adab."},

"h-ikat-unta":{t:"h",ttl:"Ikat untamu, lalu bertawakallah",
ar:"قَالَ رَجُلٌ: يَا رَسُولَ اللَّهِ، أَعْقِلُهَا وَأَتَوَكَّلُ، أَوْ أُطْلِقُهَا وَأَتَوَكَّلُ؟ قَالَ: اعْقِلْهَا وَتَوَكَّلْ",
tr:"Seorang lelaki bertanya, \"Wahai Rasulullah, kuikat untaku lalu bertawakal, atau kulepas saja lalu bertawakal?\" Beliau menjawab: \"Ikatlah ia, lalu bertawakallah.\" (dari Anas bin Malik)",
takhrij:"HR Tirmidzi no. 2517; juga diriwayatkan Ibnu Hibban dari 'Amr bin Umayyah.",
grade:"Hasan — dinilai hasan oleh al-Albani (Shahih at-Tirmidzi) dengan jalur-jalur yang saling menguatkan.",
sabab:"Asbabul wurud termuat dalam hadis: pertanyaan pemilik unta tentang makna tawakal.",
syarah:"Para ulama: tawakal yang benar berdiri di atas ikhtiar — mengambil sebab lalu menyandarkan hati kepada Allah. Maka iman MELENGKAPI bantuan profesional, bukan menggantikannya.",
note:"Kaidah pokok modul ketenangan ibu dan seluruh sikap proyek ini."},

"h-abu-umair":{t:"h",ttl:"Candaan lembut Nabi kepada anak kecil",
ar:"يَا أَبَا عُمَيْرٍ، مَا فَعَلَ النُّغَيْرُ؟",
tr:"\"Wahai Abu 'Umair, apa kabar si nughair (burung kecil)?\" — sapaan Nabi ﷺ kepada adik kecil Anas yang burung peliharaannya mati; beliau biasa bercanda lembut dengannya. (dari Anas bin Malik)",
takhrij:"HR Bukhari no. 6129; Muslim no. 2150.",
grade:"Sahih — muttafaqun 'alaih.",
sabab:"Termuat dalam hadis: Nabi ﷺ rutin mengunjungi keluarga Anas dan menyapa si kecil Abu 'Umair; ketika burungnya mati, beliau menghiburnya dengan sapaan ini.",
syarah:"Ibnu Hajar menghitung lebih dari enam puluh faedah hadis ini — di antaranya: bercanda dengan anak, menyapa anak dengan kunyah (panggilan hormat), menghibur kesedihan anak, dan turun ke dunia mereka. Anas berkhidmat sepuluh tahun dan berkata beliau manusia terbaik akhlaknya (HR Muslim no. 2309).",
note:"Keteladanan berbicara kepada anak: hangat, menghargai, setara — dalil yang sahih dan utuh."}
};
