// ====== DALIL DB — AL-QUR'AN ======
// Tiap entri: t:'q', ttl, s (no surah), a1,a2 (rentang ayat), ar (teks Arab), tr (terjemah),
// sabab (asbabun nuzul — jujur bila tak ada riwayat sahih), tafsir (inti tafsir mufassir mu'tabar), note.
var DALIL_Q = {
"q-muzzammil-73-4":{t:"q",ttl:"Al-Muzzammil 73:4 — Tartil",s:73,a1:4,a2:4,
ar:"أَوْ زِدْ عَلَيْهِ وَرَتِّلِ الْقُرْآنَ تَرْتِيلًا",
tr:"…atau lebih dari (seperdua) itu, dan bacalah Al-Qur'an itu dengan tartil (perlahan-lahan).",
sabab:"Bagian dari wahyu-wahyu awal kepada Nabi ﷺ tentang qiyamul lail; tidak ada riwayat sebab turun khusus yang sahih untuk ayat ini.",
tafsir:"Ibnu Katsir: bacalah dengan perlahan, sebab itu membantu memahami dan merenungkan maknanya — demikianlah Nabi ﷺ membaca. Ali bin Abi Thalib menafsirkan tartil: \"tajwidul-huruf wa ma'rifatul-wuquf\" — membaguskan huruf dan mengetahui tempat berhenti.",
note:"Dasar memperdengarkan bacaan yang tenang dan tertata — termasuk kepada janin dan anak."},

"q-isra-17-82":{t:"q",ttl:"Al-Isra 17:82 — Penyembuh dan rahmat",s:17,a1:82,a2:82,
ar:"وَنُنَزِّلُ مِنَ الْقُرْآنِ مَا هُوَ شِفَاءٌ وَرَحْمَةٌ لِّلْمُؤْمِنِينَ ۙ وَلَا يَزِيدُ الظَّالِمِينَ إِلَّا خَسَارًا",
tr:"Dan Kami turunkan dari Al-Qur'an sesuatu yang menjadi penyembuh dan rahmat bagi orang-orang yang beriman, sedangkan bagi orang-orang yang zalim hanya menambah kerugian.",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih.",
tafsir:"Ibnu Katsir: Al-Qur'an menyembuhkan apa yang ada di dalam hati — keraguan, kemunafikan, dan penyimpangan — serta rahmat yang membuahkan iman dan hikmah. As-Sa'di: penyembuh hati dari penyakit syahwat dan syubhat; sebagian ulama memasukkan pula keberkahan bagi badan dengan ruqyah yang disyariatkan.",
note:"Para ulama memaknai shifa terutama bagi hati dan jiwa — bukan janji medis."},

"q-sajdah-32-9":{t:"q",ttl:"As-Sajdah 32:9 — Pendengaran disebut dahulu",s:32,a1:9,a2:9,
ar:"ثُمَّ سَوَّاهُ وَنَفَخَ فِيهِ مِن رُّوحِهِ ۖ وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ ۚ قَلِيلًا مَّا تَشْكُرُونَ",
tr:"Kemudian Dia menyempurnakannya dan meniupkan roh (ciptaan)-Nya ke dalamnya, dan Dia menjadikan bagi kamu pendengaran, penglihatan, dan hati; (tetapi) sedikit sekali kamu bersyukur.",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih.",
tafsir:"Ibnu Katsir dan al-Qurthubi mencatat urutan penyebutan pendengaran sebelum penglihatan pada ayat-ayat karunia indra; sebagian ulama memetik hikmah bahwa pendengaran adalah pintu ilmu yang berfungsi paling awal. Inti ayat: indra adalah karunia untuk disyukuri dengan digunakan pada kebaikan.",
note:"Selaras dengan temuan bahwa pendengaran janin berfungsi lebih dulu daripada penglihatan."},

"q-nahl-16-78":{t:"q",ttl:"An-Nahl 16:78 — Lahir tanpa ilmu, diberi indra",s:16,a1:78,a2:78,
ar:"وَاللَّهُ أَخْرَجَكُم مِّن بُطُونِ أُمَّهَاتِكُمْ لَا تَعْلَمُونَ شَيْئًا وَجَعَلَ لَكُمُ السَّمْعَ وَالْأَبْصَارَ وَالْأَفْئِدَةَ ۙ لَعَلَّكُمْ تَشْكُرُونَ",
tr:"Dan Allah mengeluarkan kamu dari perut ibumu dalam keadaan tidak mengetahui sesuatu pun, dan Dia memberimu pendengaran, penglihatan, dan hati nurani, agar kamu bersyukur.",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih.",
tafsir:"Ibnu Katsir: manusia lahir tanpa ilmu, lalu Allah menganugerahkan alat-alat untuk memperoleh ilmu — pendengaran, penglihatan, dan af'idah (hati/akal) — yang tumbuh sedikit demi sedikit. Syukurnya adalah menggunakannya dalam ketaatan.",
note:"Fondasi memandang seluruh ranah perkembangan anak sebagai karunia yang dirawat."},

"q-muminun-23-12-14":{t:"q",ttl:"Al-Mu'minun 23:12–14 — Penciptaan bertahap",s:23,a1:12,a2:14,
ar:"وَلَقَدْ خَلَقْنَا الْإِنسَانَ مِن سُلَالَةٍ مِّن طِينٍ ﴿١٢﴾ ثُمَّ جَعَلْنَاهُ نُطْفَةً فِي قَرَارٍ مَّكِينٍ ﴿١٣﴾ ثُمَّ خَلَقْنَا النُّطْفَةَ عَلَقَةً فَخَلَقْنَا الْعَلَقَةَ مُضْغَةً فَخَلَقْنَا الْمُضْغَةَ عِظَامًا فَكَسَوْنَا الْعِظَامَ لَحْمًا ثُمَّ أَنشَأْنَاهُ خَلْقًا آخَرَ ۚ فَتَبَارَكَ اللَّهُ أَحْسَنُ الْخَالِقِينَ ﴿١٤﴾",
tr:"Dan sungguh, Kami telah menciptakan manusia dari saripati (berasal) dari tanah. Kemudian Kami menjadikannya air mani (yang disimpan) dalam tempat yang kokoh (rahim). Kemudian air mani itu Kami jadikan segumpal darah, lalu segumpal darah itu Kami jadikan segumpal daging, dan segumpal daging itu Kami jadikan tulang-belulang, lalu tulang-belulang itu Kami bungkus dengan daging. Kemudian Kami menjadikannya makhluk yang (berbentuk) lain. Maka Maha Suci Allah, Pencipta yang paling baik.",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih untuk rangkaian ayat ini.",
tafsir:"Ibnu Katsir: ayat ini menuturkan tahapan penciptaan manusia di dalam rahim sebagai bukti kekuasaan Allah, ditutup pujian \"ahsanul-khaliqin\". Para mufasir menjadikannya undangan untuk kagum dan bersyukur — bukan buku teks teknis; modul ini sengaja tidak bersandar pada klaim \"mukjizat embriologi\" yang diperdebatkan secara akademis.",
note:"Dipakai untuk makna: kekaguman dan syukur atas pembentukan janin yang bertahap."},

"q-rad-13-28":{t:"q",ttl:"Ar-Ra'd 13:28 — Hati tenang dengan dzikir",s:13,a1:28,a2:28,
ar:"الَّذِينَ آمَنُوا وَتَطْمَئِنُّ قُلُوبُهُم بِذِكْرِ اللَّهِ ۗ أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ",
tr:"(Yaitu) orang-orang yang beriman dan hati mereka menjadi tenteram dengan mengingat Allah. Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram.",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih yang disepakati untuk ayat ini.",
tafsir:"Ibnu Katsir: hati menjadi baik dan tenang dengan mengingat Allah, condong kepada-Nya, dan ridha menjadikan-Nya pelindung. As-Sa'di: kegelisahan hilang dan digantikan kegembiraan sejati ketika hati terpaut pada Allah.",
note:"Sandaran utama menjadikan dzikir, doa, dan tilawah sebagai sumber ketenangan ibu."},

"q-baqarah-2-153":{t:"q",ttl:"Al-Baqarah 2:153 — Sabar dan salat",s:2,a1:153,a2:153,
ar:"يَا أَيُّهَا الَّذِينَ آمَنُوا اسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ إِنَّ اللَّهَ مَعَ الصَّابِرِينَ",
tr:"Wahai orang-orang yang beriman! Mohonlah pertolongan (kepada Allah) dengan sabar dan salat. Sungguh, Allah beserta orang-orang yang sabar.",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih.",
tafsir:"Ibnu Katsir: Allah menjelaskan bahwa sarana terbaik menghadapi musibah adalah sabar dan salat; \"Allah beserta orang-orang sabar\" adalah kebersamaan pertolongan dan dukungan.",
note:"Dipraktikkan sebagai rutinitas hati yang menenangkan, berdampingan dengan ikhtiar nyata."},

"q-baqarah-2-168":{t:"q",ttl:"Al-Baqarah 2:168 — Halal dan tayyib",s:2,a1:168,a2:168,
ar:"يَا أَيُّهَا النَّاسُ كُلُوا مِمَّا فِي الْأَرْضِ حَلَالًا طَيِّبًا وَلَا تَتَّبِعُوا خُطُوَاتِ الشَّيْطَانِ ۚ إِنَّهُ لَكُمْ عَدُوٌّ مُّبِينٌ",
tr:"Wahai manusia! Makanlah dari (makanan) yang halal dan baik yang terdapat di bumi, dan janganlah kamu mengikuti langkah-langkah setan. Sungguh, setan itu musuh yang nyata bagimu.",
sabab:"Ath-Thabari menukil bahwa ayat ini turun berkenaan kaum yang mengharamkan atas diri mereka sebagian hewan ternak (bahirah, sa'ibah, dan semisalnya); riwayat-riwayatnya tentang konteks umum kebiasaan jahiliah, bukan satu kisah tunggal yang tegas.",
tafsir:"Ibnu Katsir: halal pada zatnya dan cara memperolehnya; thayyib berarti baik, tidak membahayakan badan dan akal. Al-Qurthubi menekankan ayat ini dasar memilih makanan yang bersih dan menyehatkan.",
note:"Bingkai gizi: halal, baik, dan menyehatkan — selaras pola makan seimbang."},

"q-araf-7-31":{t:"q",ttl:"Al-A'raf 7:31 — Jangan berlebihan",s:7,a1:31,a2:31,
ar:"يَا بَنِي آدَمَ خُذُوا زِينَتَكُمْ عِندَ كُلِّ مَسْجِدٍ وَكُلُوا وَاشْرَبُوا وَلَا تُسْرِفُوا ۚ إِنَّهُ لَا يُحِبُّ الْمُسْرِفِينَ",
tr:"Wahai anak cucu Adam! Pakailah pakaianmu yang bagus pada setiap (memasuki) masjid, makan dan minumlah, tetapi jangan berlebihan. Sungguh, Allah tidak menyukai orang yang berlebih-lebihan.",
sabab:"Diriwayatkan dari Ibnu Abbas bahwa bagian awal ayat turun terkait kebiasaan sebagian orang jahiliah bertawaf tanpa pakaian (riwayat Muslim no. 3028 menyebut konteks ini); perintah makan-minum tanpa israf berlaku umum.",
tafsir:"Ibnu Katsir menukil ucapan sebagian salaf: \"Allah mengumpulkan seluruh pengobatan dalam setengah ayat ini — makan, minum, dan jangan berlebihan.\" As-Sa'di: israf mencakup melampaui batas dalam kadar maupun jenisnya.",
note:"Penopang prinsip \"cukup dan seimbang\" — bukan \"makan untuk dua orang\"."},

"q-maryam-19-25-26":{t:"q",ttl:"Maryam 19:25–26 — Kurma bagi Maryam",s:19,a1:25,a2:26,
ar:"وَهُزِّي إِلَيْكِ بِجِذْعِ النَّخْلَةِ تُسَاقِطْ عَلَيْكِ رُطَبًا جَنِيًّا ﴿٢٥﴾ فَكُلِي وَاشْرَبِي وَقَرِّي عَيْنًا ۖ ...",
tr:"Dan goyanglah pangkal pohon kurma itu ke arahmu, niscaya (pohon) itu akan menggugurkan buah kurma yang masak kepadamu. Maka makan, minum, dan bersenanghatilah engkau…",
sabab:"Bagian dari kisah kelahiran Nabi Isa; konteksnya adalah penghiburan Allah kepada Maryam saat persalinan.",
tafsir:"Ibnu Katsir: Allah mengaruniakan rezeki ruthab (kurma segar) kepada Maryam saat melahirkan; sebagian ulama dan tabib menyebut kurma segar bermanfaat bagi wanita nifas — sebagai hikmah, bukan resep medis dari ayat.",
note:"Kurma masuk sebagai makanan tayyib; bukti modern yang ada menyangkut persalinan, bukan kecerdasan."},

"q-ali-imran-3-38":{t:"q",ttl:"Ali 'Imran 3:38 — Doa Zakariya",s:3,a1:38,a2:38,
ar:"هُنَالِكَ دَعَا زَكَرِيَّا رَبَّهُ ۖ قَالَ رَبِّ هَبْ لِي مِن لَّدُنكَ ذُرِّيَّةً طَيِّبَةً ۖ إِنَّكَ سَمِيعُ الدُّعَاءِ",
tr:"Di sanalah Zakariya berdoa kepada Tuhannya. Ia berkata, \"Ya Tuhanku, berilah aku keturunan yang baik dari sisi-Mu; sesungguhnya Engkau Maha Mendengar doa.\"",
sabab:"Konteksnya kisah Zakariya yang terdorong berdoa setelah menyaksikan rezeki Maryam di mihrab.",
tafsir:"Ibnu Katsir: melihat karunia Allah pada Maryam membangkitkan harap Zakariya akan anak, padahal usianya lanjut — maka ia memohon dzurriyyah thayyibah, keturunan yang saleh.",
note:"Doa Qur'ani memohon keturunan yang baik — diamalkan sejak masa menanti."},

"q-saffat-37-100":{t:"q",ttl:"Ash-Shaffat 37:100 — Doa Ibrahim",s:37,a1:100,a2:100,
ar:"رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ",
tr:"Ya Tuhanku, anugerahkanlah kepadaku (seorang anak) yang termasuk orang-orang saleh.",
sabab:"Doa Nabi Ibrahim setelah berhijrah meninggalkan kaumnya; Allah lalu memberinya kabar gembira seorang anak yang sangat sabar (ayat 101).",
tafsir:"Ibnu Katsir: Ibrahim memohon anak yang saleh sebagai pengganti kaum yang ditinggalkannya, dan Allah mengabulkan dengan Ismail. Inti doanya: yang diminta bukan sekadar anak, melainkan kesalehannya.",
note:"Teladan doa: memohon kualitas (saleh), bukan hanya kehadiran anak."},

"q-furqan-25-74":{t:"q",ttl:"Al-Furqan 25:74 — Penyejuk mata",s:25,a1:74,a2:74,
ar:"وَالَّذِينَ يَقُولُونَ رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
tr:"Dan orang-orang yang berkata, \"Ya Tuhan kami, anugerahkanlah kepada kami pasangan kami dan keturunan kami sebagai penyenang hati (kami), dan jadikanlah kami pemimpin bagi orang-orang yang bertakwa.\"",
sabab:"Bagian dari sifat-sifat 'ibadurrahman; tidak ada riwayat sebab turun khusus yang sahih.",
tafsir:"Ibnu Katsir menukil al-Hasan al-Bashri: penyejuk mata itu adalah melihat keluarga taat kepada Allah — \"tidak ada yang lebih menyejukkan mata seorang mukmin daripada melihat anak dan pasangannya taat kepada Allah.\"",
note:"Doa harian orang tua: keluarga yang menjadi qurrata a'yun."},

"q-ali-imran-3-35-36":{t:"q",ttl:"Ali 'Imran 3:35–36 — Nazar ibunda Maryam",s:3,a1:35,a2:36,
ar:"إِذْ قَالَتِ امْرَأَتُ عِمْرَانَ رَبِّ إِنِّي نَذَرْتُ لَكَ مَا فِي بَطْنِي مُحَرَّرًا فَتَقَبَّلْ مِنِّي ۖ إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ ﴿٣٥﴾ فَلَمَّا وَضَعَتْهَا قَالَتْ رَبِّ إِنِّي وَضَعْتُهَا أُنثَىٰ ... وَإِنِّي سَمَّيْتُهَا مَرْيَمَ وَإِنِّي أُعِيذُهَا بِكَ وَذُرِّيَّتَهَا مِنَ الشَّيْطَانِ الرَّجِيمِ ﴿٣٦﴾",
tr:"(Ingatlah) ketika istri Imran berkata, \"Ya Tuhanku, sesungguhnya aku bernazar kepada-Mu, apa (janin) yang dalam kandunganku (kelak) menjadi hamba yang mengabdi (kepada-Mu), maka terimalah (nazar itu) dariku…\" Maka ketika melahirkannya, ia berkata, \"…aku memberinya nama Maryam, dan aku memohon perlindungan-Mu untuknya dan anak keturunannya dari setan yang terkutuk.\"",
sabab:"Kisah keluarga Imran; menjadi teladan penyerahan anak kepada Allah sejak dalam kandungan.",
tafsir:"Ibnu Katsir: ibunda Maryam menazarkan kandungannya untuk berkhidmat di Baitul Maqdis, lalu memohonkan perlindungan bagi anak dan keturunannya — Allah menerima Maryam dengan penerimaan yang baik.",
note:"Teladan: niat, penamaan yang baik, dan doa perlindungan bagi anak dimulai sejak hamil."},

"q-rahman-55-3-4":{t:"q",ttl:"Ar-Rahman 55:3–4 — Diajari al-bayan",s:55,a1:3,a2:4,
ar:"خَلَقَ الْإِنسَانَ ﴿٣﴾ عَلَّمَهُ الْبَيَانَ ﴿٤﴾",
tr:"Dia menciptakan manusia. Dia mengajarinya pandai menjelaskan (al-bayan).",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih.",
tafsir:"Ibnu Katsir: al-bayan adalah kemampuan berbicara/mengungkapkan; al-Hasan: an-nuthq (bertutur). Ath-Thabari memaknainya luas: kemampuan menjelaskan apa yang ada dalam diri. Bahasa adalah karunia pembeda yang Allah sebut langsung setelah penciptaan manusia.",
note:"Menumbuhkan bahasa anak = memuliakan salah satu karunia terbesar."},

"q-baqarah-2-83":{t:"q",ttl:"Al-Baqarah 2:83 — Berkata baik kepada manusia",s:2,a1:83,a2:83,
ar:"... وَقُولُوا لِلنَّاسِ حُسْنًا ...",
tr:"…serta bertutur katalah yang baik kepada manusia…",
sabab:"Bagian dari perjanjian Allah dengan Bani Israil yang diabadikan sebagai pelajaran umum.",
tafsir:"Ibnu Katsir menukil al-Hasan al-Bashri tentang \"husna\": memerintahkan yang makruf, mencegah yang mungkar, sabar, pemaaf — dan berkata kepada manusia dengan perkataan yang baik. Berlaku kepada semua orang.",
note:"Lingkungan bahasa anak: diisi tutur yang baik."},

"q-ibrahim-14-24-25":{t:"q",ttl:"Ibrahim 14:24–25 — Kalimah tayyibah",s:14,a1:24,a2:25,
ar:"أَلَمْ تَرَ كَيْفَ ضَرَبَ اللَّهُ مَثَلًا كَلِمَةً طَيِّبَةً كَشَجَرَةٍ طَيِّبَةٍ أَصْلُهَا ثَابِتٌ وَفَرْعُهَا فِي السَّمَاءِ ﴿٢٤﴾ تُؤْتِي أُكُلَهَا كُلَّ حِينٍ بِإِذْنِ رَبِّهَا ۗ ...",
tr:"Tidakkah kamu memperhatikan bagaimana Allah telah membuat perumpamaan kalimat yang baik seperti pohon yang baik, akarnya kuat dan cabangnya (menjulang) ke langit. (Pohon) itu menghasilkan buahnya pada setiap waktu dengan seizin Tuhannya…",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih.",
tafsir:"Ibnu Katsir menukil Ibnu Abbas: kalimah tayyibah adalah syahadat la ilaha illallah, dan pohon yang baik adalah (perumpamaan) orang mukmin — akarnya kukuh di hati, amalnya naik ke langit. Para ulama memperluas: setiap perkataan baik berakar dan berbuah.",
note:"Perumpamaan bagi menanam kata-kata baik sejak dini."},

"q-qamar-54-49":{t:"q",ttl:"Al-Qamar 54:49 — Segala sesuatu menurut ukuran",s:54,a1:49,a2:49,
ar:"إِنَّا كُلَّ شَيْءٍ خَلَقْنَاهُ بِقَدَرٍ",
tr:"Sungguh, Kami menciptakan segala sesuatu menurut ukuran (qadar).",
sabab:"Diriwayatkan ayat ini turun berkenaan bantahan kepada kaum musyrik yang mendebat tentang takdir (riwayat Muslim no. 2656 dari Abu Hurairah menyebut konteks kedatangan musyrikin Quraisy mendebat qadar).",
tafsir:"Ibnu Katsir: ayat ini dalil bahwa Allah menetapkan kadar segala sesuatu sebelum menciptakannya — termasuk dalil ahlussunnah tentang takdir. As-Sa'di: mencakup pula keteraturan dan ketepatan ukuran pada ciptaan. Konteks utamanya adalah qadar (ketetapan Allah); keteraturan alam adalah cabang maknanya.",
note:"Untuk balita cukup kegembiraan menemukan pola; makna qadar dipegang orang tua."},

"q-furqan-25-2":{t:"q",ttl:"Al-Furqan 25:2 — Menetapkan ukuran dengan tepat",s:25,a1:2,a2:2,
ar:"... وَخَلَقَ كُلَّ شَيْءٍ فَقَدَّرَهُ تَقْدِيرًا",
tr:"…dan Dia menciptakan segala sesuatu, lalu menetapkan ukuran-ukurannya dengan tepat.",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih.",
tafsir:"Ibnu Katsir: segala sesuatu selain Allah adalah makhluk yang diatur-Nya dengan penetapan yang rapi — tidak ada yang sia-sia atau kebetulan.",
note:"Keteraturan ciptaan mengundang kekaguman — benih tafakkur."},

"q-ala-87-2-3":{t:"q",ttl:"Al-A'la 87:2–3 — Menyempurnakan dan menentukan kadar",s:87,a1:2,a2:3,
ar:"الَّذِي خَلَقَ فَسَوَّىٰ ﴿٢﴾ وَالَّذِي قَدَّرَ فَهَدَىٰ ﴿٣﴾",
tr:"Yang menciptakan, lalu menyempurnakan (ciptaan-Nya). Yang menentukan kadar (masing-masing) dan memberi petunjuk.",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih.",
tafsir:"Ibnu Katsir: Allah menentukan kadar lalu menunjukkan tiap makhluk kepada (jalan) yang sesuai baginya; mencakup hidayah umum pada seluruh ciptaan.",
note:"Perkembangan bertahap anak pun berjalan menurut kadar yang Allah tetapkan."},

"q-ali-imran-3-190-191":{t:"q",ttl:"Ali 'Imran 3:190–191 — Ulul albab dan tafakkur",s:3,a1:190,a2:191,
ar:"إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ وَاخْتِلَافِ اللَّيْلِ وَالنَّهَارِ لَآيَاتٍ لِّأُولِي الْأَلْبَابِ ﴿١٩٠﴾ الَّذِينَ يَذْكُرُونَ اللَّهَ قِيَامًا وَقُعُودًا وَعَلَىٰ جُنُوبِهِمْ وَيَتَفَكَّرُونَ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ رَبَّنَا مَا خَلَقْتَ هَٰذَا بَاطِلًا سُبْحَانَكَ فَقِنَا عَذَابَ النَّارِ ﴿١٩١﴾",
tr:"Sesungguhnya dalam penciptaan langit dan bumi, dan pergantian malam dan siang terdapat tanda-tanda (kebesaran Allah) bagi orang yang berakal, (yaitu) orang-orang yang mengingat Allah sambil berdiri, duduk, atau dalam keadaan berbaring, dan mereka memikirkan tentang penciptaan langit dan bumi (seraya berkata), \"Ya Tuhan kami, tidaklah Engkau menciptakan semua ini sia-sia; Maha Suci Engkau, lindungilah kami dari azab neraka.\"",
sabab:"Dalam Sahih Bukhari (no. 4569 dst.) dan Muslim (no. 763) disebutkan Nabi ﷺ membaca ayat-ayat penutup Ali 'Imran ini ketika bangun untuk salat malam — menunjukkan kedudukannya dalam ibadah tafakkur; bukan riwayat sebab turun.",
tafsir:"Ibnu Katsir: ulul albab adalah akal yang sempurna — memadukan dzikir lisan-hati dengan tafakkur atas ciptaan. Diriwayatkan Nabi ﷺ menangis ketika ayat ini turun dan bersabda: \"Celakalah orang yang membacanya namun tidak merenungkannya\" (riwayat Ibnu Hibban; sanadnya diperbincangkan).",
note:"Tafakkur adalah ibadah akal — pada anak, benihnya adalah gembira mengamati."},

"q-ghasyiyah-88-17-20":{t:"q",ttl:"Al-Ghasyiyah 88:17–20 — Tidakkah mereka memperhatikan",s:88,a1:17,a2:20,
ar:"أَفَلَا يَنظُرُونَ إِلَى الْإِبِلِ كَيْفَ خُلِقَتْ ﴿١٧﴾ وَإِلَى السَّمَاءِ كَيْفَ رُفِعَتْ ﴿١٨﴾ وَإِلَى الْجِبَالِ كَيْفَ نُصِبَتْ ﴿١٩﴾ وَإِلَى الْأَرْضِ كَيْفَ سُطِحَتْ ﴿٢٠﴾",
tr:"Maka tidakkah mereka memperhatikan unta, bagaimana diciptakan? Dan langit, bagaimana ditinggikan? Dan gunung-gunung, bagaimana ditegakkan? Dan bumi, bagaimana dihamparkan?",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih.",
tafsir:"Ibnu Katsir: Allah memerintahkan memperhatikan makhluk-makhluk yang terhampar di depan mata — dimulai dari unta yang akrab bagi orang Arab — sebagai pintu mengenali kebesaran Penciptanya.",
note:"Mengamati alam bersama anak adalah mengamalkan undangan ayat ini, tanpa menggurui."},

"q-dzariyat-51-20-21":{t:"q",ttl:"Adz-Dzariyat 51:20–21 — Tanda di bumi dan diri",s:51,a1:20,a2:21,
ar:"وَفِي الْأَرْضِ آيَاتٌ لِّلْمُوقِنِينَ ﴿٢٠﴾ وَفِي أَنفُسِكُمْ ۚ أَفَلَا تُبْصِرُونَ ﴿٢١﴾",
tr:"Dan di bumi terdapat tanda-tanda (kebesaran Allah) bagi orang-orang yang yakin, dan (juga) pada dirimu sendiri. Maka apakah kamu tidak memperhatikan?",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih.",
tafsir:"Ibnu Katsir: di bumi ada tanda-tanda — tetumbuhan, hewan, gunung, dan keragaman makhluk; dan pada diri manusia — susunan tubuh dan kemampuannya. Qatadah: siapa bertafakkur pada penciptaan dirinya, tahulah ia bahwa ia diciptakan untuk ibadah.",
note:"Daun, semut, air — dan tubuh ananda sendiri — semuanya pintu kekaguman."},

"q-qalam-68-4":{t:"q",ttl:"Al-Qalam 68:4 — Akhlak yang agung",s:68,a1:4,a2:4,
ar:"وَإِنَّكَ لَعَلَىٰ خُلُقٍ عَظِيمٍ",
tr:"Dan sesungguhnya engkau benar-benar berbudi pekerti yang luhur.",
sabab:"Pujian Allah kepada Nabi ﷺ pada awal masa kenabian, membantah tuduhan kaum musyrik.",
tafsir:"Ibnu Katsir menukil jawaban Aisyah ketika ditanya akhlak Nabi: \"Akhlak beliau adalah Al-Qur'an\" (HR Muslim no. 746). Khuluq 'azhim mencakup adab-adab Al-Qur'an yang beliau jalankan seluruhnya.",
note:"Teladan tertinggi akhlak — tujuan pengasuhan hati."},

"q-saff-61-2-3":{t:"q",ttl:"Ash-Shaff 61:2–3 — Selaras kata dan perbuatan",s:61,a1:2,a2:3,
ar:"يَا أَيُّهَا الَّذِينَ آمَنُوا لِمَ تَقُولُونَ مَا لَا تَفْعَلُونَ ﴿٢﴾ كَبُرَ مَقْتًا عِندَ اللَّهِ أَن تَقُولُوا مَا لَا تَفْعَلُونَ ﴿٣﴾",
tr:"Wahai orang-orang yang beriman! Mengapa kamu mengatakan sesuatu yang tidak kamu kerjakan? (Itu) sangat dibenci di sisi Allah jika kamu mengatakan apa yang tidak kamu kerjakan.",
sabab:"Ibnu Katsir menukil riwayat bahwa sebagian sahabat berkata \"seandainya kami tahu amal yang paling dicintai Allah, kami kerjakan\", lalu ketika diturunkan perintah jihad sebagian merasa berat — maka turunlah teguran ini (riwayat Tirmidzi, dinilai sahih oleh sebagian ulama).",
tafsir:"Ibnu Katsir: ini pengingkaran atas orang yang berjanji atau berkata lalu tidak menepati; para ulama menjadikannya dalil keharusan keselarasan ucapan dan perbuatan — inti keteladanan.",
note:"Anak meniru yang dilihat: teladan adalah pengajaran yang paling jujur."},

"q-ahzab-33-21":{t:"q",ttl:"Al-Ahzab 33:21 — Uswah hasanah",s:33,a1:21,a2:21,
ar:"لَّقَدْ كَانَ لَكُمْ فِي رَسُولِ اللَّهِ أُسْوَةٌ حَسَنَةٌ لِّمَن كَانَ يَرْجُو اللَّهَ وَالْيَوْمَ الْآخِرَ وَذَكَرَ اللَّهَ كَثِيرًا",
tr:"Sungguh, telah ada pada (diri) Rasulullah itu suri teladan yang baik bagimu, (yaitu) bagi orang yang mengharap (rahmat) Allah dan (kedatangan) hari Kiamat dan yang banyak mengingat Allah.",
sabab:"Turun dalam konteks Perang Ahzab (Khandaq): keteladanan Nabi ﷺ dalam kesabaran dan perjuangan.",
tafsir:"Ibnu Katsir: ayat ini pokok agung dalam meneladani Rasulullah ﷺ pada ucapan, perbuatan, dan keadaan beliau.",
note:"Dasar menjadikan keteladanan sebagai metode utama mendidik."},

"q-hujurat-49-6":{t:"q",ttl:"Al-Hujurat 49:6 — Tabayyun",s:49,a1:6,a2:6,
ar:"يَا أَيُّهَا الَّذِينَ آمَنُوا إِن جَاءَكُمْ فَاسِقٌ بِنَبَإٍ فَتَبَيَّنُوا أَن تُصِيبُوا قَوْمًا بِجَهَالَةٍ فَتُصْبِحُوا عَلَىٰ مَا فَعَلْتُمْ نَادِمِينَ",
tr:"Wahai orang-orang yang beriman! Jika seseorang yang fasik datang kepadamu membawa suatu berita, maka telitilah kebenarannya, agar kamu tidak mencelakakan suatu kaum karena ketidaktahuan (kecerobohan), yang akhirnya kamu menyesali perbuatanmu itu.",
sabab:"Mayoritas mufasir (Ibnu Katsir, ath-Thabari) menyebut ayat ini turun berkenaan al-Walid bin 'Uqbah yang dikirim memungut zakat Bani Mushthaliq lalu kembali membawa kabar keliru bahwa mereka menolak; riwayat-riwayatnya saling menguatkan meski sebagian sanadnya diperbincangkan.",
tafsir:"Ibnu Katsir: wajib memastikan kebenaran berita orang fasik agar tidak menghukumi dengan persangkaan. Inilah akar adab verifikasi dalam Islam.",
note:"Tabayyun = literasi sumber: periksa sebelum meneruskan."},

"q-isra-17-36":{t:"q",ttl:"Al-Isra 17:36 — Jangan ikuti tanpa ilmu",s:17,a1:36,a2:36,
ar:"وَلَا تَقْفُ مَا لَيْسَ لَكَ بِهِ عِلْمٌ ۚ إِنَّ السَّمْعَ وَالْبَصَرَ وَالْفُؤَادَ كُلُّ أُولَٰئِكَ كَانَ عَنْهُ مَسْئُولًا",
tr:"Dan janganlah kamu mengikuti sesuatu yang tidak kamu ketahui. Karena pendengaran, penglihatan, dan hati nurani, semua itu akan diminta pertanggungjawabannya.",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih; bagian dari rangkaian wasiat-wasiat Al-Isra.",
tafsir:"Ibnu Katsir menukil Qatadah: jangan berkata \"aku melihat/mendengar\" padahal tidak. Indra dan hati akan ditanya tentang apa yang dipakai meyakini dan menyebarkan sesuatu.",
note:"Setiap klaim yang kita wariskan kepada anak harus berilmu."},

"q-baqarah-2-286":{t:"q",ttl:"Al-Baqarah 2:286 — Tidak dibebani melebihi kesanggupan",s:2,a1:286,a2:286,
ar:"لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا ۚ ...",
tr:"Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya…",
sabab:"Dalam Sahih Muslim (no. 125–126) diriwayatkan para sahabat merasa berat oleh ayat sebelumnya (2:284) lalu Allah menurunkan ayat ini sebagai keringanan dan Allah berfirman \"Aku telah melakukannya\" atas tiap doanya.",
tafsir:"Ibnu Katsir: kelembutan Allah pada makhluk — Dia tidak menuntut di luar kemampuan; ayat ini menghapus kegelisahan atas lintasan hati yang tak terucap dan tak diamalkan.",
note:"Batas diri orang tua itu nyata dan diakui — bukan sumber rasa bersalah."},

"q-tahrim-66-6":{t:"q",ttl:"At-Tahrim 66:6 — Jagalah keluargamu",s:66,a1:6,a2:6,
ar:"يَا أَيُّهَا الَّذِينَ آمَنُوا قُوا أَنفُسَكُمْ وَأَهْلِيكُمْ نَارًا وَقُودُهَا النَّاسُ وَالْحِجَارَةُ ...",
tr:"Wahai orang-orang yang beriman! Peliharalah dirimu dan keluargamu dari api neraka yang bahan bakarnya adalah manusia dan batu…",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih.",
tafsir:"Ibnu Katsir menukil Ali bin Abi Thalib: \"addibuhum wa 'allimuhum\" — didiklah adab mereka dan ajarilah mereka. Qatadah: perintahkan keluarga taat dan cegah dari maksiat, tegakkan perintah Allah atas mereka dan bantu mereka menjalankannya.",
note:"Dalil pokok tanggung jawab pendidikan keluarga — dijalani dengan ilmu dan kasih."},

"q-ali-imran-3-159":{t:"q",ttl:"Ali 'Imran 3:159 — Lemah lembut, lalu tawakal",s:3,a1:159,a2:159,
ar:"فَبِمَا رَحْمَةٍ مِّنَ اللَّهِ لِنتَ لَهُمْ ۖ وَلَوْ كُنتَ فَظًّا غَلِيظَ الْقَلْبِ لَانفَضُّوا مِنْ حَوْلِكَ ۖ فَاعْفُ عَنْهُمْ وَاسْتَغْفِرْ لَهُمْ وَشَاوِرْهُمْ فِي الْأَمْرِ ۖ فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى اللَّهِ ۚ إِنَّ اللَّهَ يُحِبُّ الْمُتَوَكِّلِينَ",
tr:"Maka berkat rahmat Allah engkau (Muhammad) berlaku lemah lembut terhadap mereka. Sekiranya engkau bersikap keras dan berhati kasar, tentulah mereka menjauhkan diri dari sekitarmu. Karena itu maafkanlah mereka, mohonkanlah ampunan untuk mereka, dan bermusyawarahlah dengan mereka dalam urusan itu. Kemudian, apabila engkau telah membulatkan tekad, maka bertawakallah kepada Allah. Sungguh, Allah mencintai orang yang bertawakal.",
sabab:"Turun setelah Perang Uhud: Allah memuji kelembutan Nabi ﷺ kepada para sahabat yang sempat tergelincir, dan memerintahkan tetap bermusyawarah.",
tafsir:"Ibnu Katsir: kelembutan beliau adalah rahmat Allah; kekerasan hati membuat manusia lari. Urutan ayat: maafkan → musyawarah → tekad → tawakal — pola pengambilan keputusan yang lembut dan berserah.",
note:"Lembut dalam mendidik, musyawarah dalam keluarga, tawakal atas hasil."},

"q-rum-30-21":{t:"q",ttl:"Ar-Rum 30:21 — Mawaddah wa rahmah",s:30,a1:21,a2:21,
ar:"وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَاجًا لِّتَسْكُنُوا إِلَيْهَا وَجَعَلَ بَيْنَكُم مَّوَدَّةً وَرَحْمَةً ۚ إِنَّ فِي ذَٰلِكَ لَآيَاتٍ لِّقَوْمٍ يَتَفَكَّرُونَ",
tr:"Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang. Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Allah) bagi kaum yang berpikir.",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih.",
tafsir:"Ibnu Katsir: sakinah, mawaddah, dan rahmah adalah anugerah Allah pada pernikahan — kasih yang menumbuhkan ketenangan, dan sayang yang membuahkan anak serta saling membutuhkan.",
note:"Fondasi pengasuhan berdua: kasih dan sayang yang Allah letakkan."},

"q-baqarah-2-187":{t:"q",ttl:"Al-Baqarah 2:187 — Pakaian bagi satu sama lain",s:2,a1:187,a2:187,
ar:"... هُنَّ لِبَاسٌ لَّكُمْ وَأَنتُمْ لِبَاسٌ لَّهُنَّ ...",
tr:"…Mereka adalah pakaian bagimu, dan kamu adalah pakaian bagi mereka…",
sabab:"Ayat ini turun berkenaan keringanan hukum malam Ramadan bagi suami-istri (disebutkan dalam Sahih Bukhari no. 4508 dari al-Bara').",
tafsir:"Ibnu Katsir menukil Ibnu Abbas dan Mujahid: pakaian bermakna sakan — ketenangan; suami-istri saling menutupi, menghangatkan, dan melindungi sebagaimana pakaian bagi tubuh.",
note:"Saling menjaga dan menutupi kekurangan — budaya rumah yang mengasuh."},

"q-baqarah-2-233":{t:"q",ttl:"Al-Baqarah 2:233 — Musyawarah urusan anak",s:2,a1:233,a2:233,
ar:"... فَإِنْ أَرَادَا فِصَالًا عَن تَرَاضٍ مِّنْهُمَا وَتَشَاوُرٍ فَلَا جُنَاحَ عَلَيْهِمَا ۗ ...",
tr:"…Apabila keduanya ingin menyapih (sebelum dua tahun) dengan kerelaan keduanya dan permusyawaratan, maka tidak ada dosa atas keduanya…",
sabab:"Bagian dari rangkaian hukum penyusuan; tidak ada kisah sebab turun khusus yang sahih.",
tafsir:"Ibnu Katsir (menukil ats-Tsauri dan lainnya): keputusan menyapih — urusan anak — diambil dengan kerelaan dan musyawarah kedua orang tua, demi kemaslahatan anak; satu pihak tidak memutuskan sendiri.",
note:"Al-Qur'an menyebut musyawarah justru pada urusan pengasuhan — model keputusan keluarga."},

"q-syura-42-38":{t:"q",ttl:"Asy-Syura 42:38 — Urusan dengan musyawarah",s:42,a1:38,a2:38,
ar:"وَالَّذِينَ اسْتَجَابُوا لِرَبِّهِمْ وَأَقَامُوا الصَّلَاةَ وَأَمْرُهُمْ شُورَىٰ بَيْنَهُمْ وَمِمَّا رَزَقْنَاهُمْ يُنفِقُونَ",
tr:"Dan (bagi) orang-orang yang menerima (mematuhi) seruan Tuhan dan melaksanakan salat, sedangkan urusan mereka (diputuskan) dengan musyawarah antara mereka; dan mereka menginfakkan sebagian dari rezeki yang Kami berikan kepada mereka.",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih; memuji sifat kaum Anshar yang biasa bermusyawarah.",
tafsir:"Ibnu Katsir: mereka tidak memutuskan suatu urusan hingga saling bermusyawarah agar saling menguatkan pendapat — prinsip umum pengambilan keputusan bersama.",
note:"Syura sebagai prinsip — termasuk musyawarah rutin pasangan."},

"q-luqman-31-13":{t:"q",ttl:"Luqman 31:13 — Nasihat dengan kasih",s:31,a1:13,a2:13,
ar:"وَإِذْ قَالَ لُقْمَانُ لِابْنِهِ وَهُوَ يَعِظُهُ يَا بُنَيَّ لَا تُشْرِكْ بِاللَّهِ ۖ إِنَّ الشِّرْكَ لَظُلْمٌ عَظِيمٌ",
tr:"Dan (ingatlah) ketika Luqman berkata kepada anaknya, ketika ia memberi pelajaran kepadanya, \"Wahai anakku! Janganlah engkau mempersekutukan Allah; sesungguhnya mempersekutukan (Allah) adalah benar-benar kezaliman yang besar.\"",
sabab:"Tidak ada riwayat sebab turun khusus yang sahih untuk ayat ini.",
tafsir:"Ibnu Katsir: Luqman menasihati anaknya — orang yang paling dikasihinya — dimulai dari tauhid; panggilan \"ya bunayya\" (wahai anakku sayang) menunjukkan kelembutan dalam mendidik. Para ulama menjadikan rangkaian wasiat Luqman model pendidikan bertahap: akidah, lalu ibadah, lalu akhlak.",
note:"Model nasihat: dimulai dari yang terpenting, dengan panggilan kasih."}
};
