// ====== BANK KUIS — 5 soal per modul, penjelasan + rujukan kartu dalil ======
var QUIZ = {
"T3-01":[
{q:"Suara siapa yang paling jernih sampai ke janin di trimester ketiga?",
 opts:["Suara ibu sendiri","Speaker yang ditempel di perut","Suara televisi","Suara dari headphone ibu"],a:0,
 ex:"Suara ibu merambat dari dalam tubuh sehingga paling sedikit teredam — irama dan nadanya terjaga (Voegtline dkk. 2013). Speaker di perut justru tidak dianjurkan."},
{q:"Apa status dalil klaim “surah tertentu membuat anak cerdas”?",
 opts:["Hadis sahih","Hadis hasan","Tidak ada dalil khusus yang sahih","Ijma ulama"],a:2,
 ex:"Tidak ada dalil khusus yang sahih untuk klaim surah-spesifik; yang berdasar adalah keutamaan tilawah dan ketenangan secara umum (Al-Isra 17:82; Al-Muzzammil 73:4).",d:["q-isra-17-82","q-muzzammil-73-4"]},
{q:"Tujuan paling jujur dari memperdengarkan tilawah pada janin adalah…",
 opts:["Menaikkan IQ bayi","Kedekatan, ketenangan, dan pembiasaan ibadah","Menjamin anak hafiz","Mempercepat bicara"],a:1,
 ex:"Modul ini menegaskan: praktik suara menumbuhkan kedekatan dan ketenangan — bukan jaminan hasil kognitif."},
{q:"Perintah “warattilil-qur’ana tartila” (Al-Muzzammil 73:4) berarti membaca dengan…",
 opts:["Secepat mungkin","Perlahan, jelas, dan tertata","Suara sekeras mungkin","Hanya dalam hati"],a:1,
 ex:"Tartil: perlahan dan jelas huruf serta berhentinya — bacaan yang indah dan tenang inilah yang dihadiahkan ke telinga ananda.",d:["q-muzzammil-73-4"]},
{q:"Janin mulai dapat mendengar dan merespons suara sekitar…",
 opts:["Minggu ke-8","Minggu ke-25 ke atas (trimester ketiga makin peka)","Hanya setelah lahir","Minggu ke-4"],a:1,
 ex:"Pendengaran janin berkembang hingga responsnya jelas pada trimester ketiga — karunia pendengaran disebut dalam An-Nahl 16:78.",d:["q-nahl-16-78","q-sajdah-32-9"]}],

"T3-02":[
{q:"Mengapa gerak janin penting bagi tubuhnya sendiri?",
 opts:["Sekadar tanda lapar","Otot, saraf, tulang, dan sendi “berlatih” lewat gerak","Mengurangi berat lahir","Tidak ada fungsinya"],a:1,
 ex:"Gerak adalah latihan perkembangan: membantu otot-saraf dan pembentukan tulang serta sendi (riset perkembangan rangka janin)."},
{q:"Saat ibu membelai perut, riset USG 4D (Marx & Nagy 2015) menemukan janin…",
 opts:["Selalu diam","Menambah respons gerakan","Berhenti tumbuh","Tertidur seketika"],a:1,
 ex:"Janin merespons sentuhan ibu dengan menambah gerakan — sentuhan adalah komunikasi dua arah pertama."},
{q:"Arah pemaknaan Al-Mu’minun 23:12–14 menurut para mufasir adalah…",
 opts:["Rincian embriologi modern","Kebesaran Allah dalam penciptaan bertahap","Resep gizi kehamilan","Hukum fiqh kandungan"],a:1,
 ex:"Ayat ini tentang keagungan Allah dalam tahapan penciptaan; kita tidak bersandar pada klaim “mukjizat embriologi” yang diperdebatkan secara akademis.",d:["q-muminun-23-12-14"]},
{q:"Memantau gerak harian janin paling baik dilakukan dengan…",
 opts:["Menebak-nebak saja","Kebiasaan mengenali pola gerak + protokol dari dokter/bidan","Mengabaikannya","USG mandiri setiap hari"],a:1,
 ex:"Kepekaan pada pola gerak adalah sarana pemantauan; protokol hitung gerak dan tindak lanjut tetap bersama tenaga kesehatan."},
{q:"“Sayangilah siapa yang di bumi…” (HR Abu Dawud no. 4941) mengajarkan bahwa membelai janin adalah…",
 opts:["Teknik berpahala khusus yang ditetapkan","Bagian budaya rahmah, bukan ritual tertentu","Kewajiban syar’i","Sia-sia"],a:1,
 ex:"Yang berdasar adalah relasi kasih dan syukur — rahmah kepada semua makhluk — bukan tata cara sentuhan tertentu yang dianggap ibadah khusus.",d:["h-rahimun"]}],

"T3-03":[
{q:"Pesan paling penting modul ketenangan ibu adalah…",
 opts:["Stres sedikit pun merusak janin","Rasa cemas itu dosa","Stres berat memengaruhi, tapi bukan vonis — yang membantu adalah dukungan","Ibu harus selalu bahagia"],a:2,
 ex:"Stres berat dapat berpengaruh lewat hormon dan plasenta (Tadanki dkk. 2025), tetapi ini pengaruh, bukan vonis — menambah rasa bersalah justru kontraproduktif (Annual Review 2024)."},
{q:"“Ingatlah, dengan mengingat Allah hati menjadi tenteram” adalah ayat…",
 opts:["Ar-Ra’d 13:28","Al-Falaq 113:1","Al-Kahfi 18:10","An-Nas 114:1"],a:0,
 ex:"Ar-Ra’d 13:28 — dzikir adalah jalan ketenangan yang dirawat, bukan dipaksakan.",d:["q-rad-13-28"]},
{q:"Kaidah “ikatlah untamu, lalu bertawakallah” (HR Tirmidzi no. 2517) berarti…",
 opts:["Tawakal meniadakan ikhtiar","Iman menggantikan bantuan profesional","Ikhtiar dan tawakal berjalan bersama — iman melengkapi bantuan","Berobat tanda lemah iman"],a:2,
 ex:"Tawakal yang benar berdiri di atas sebab: dzikir dan doa berjalan bersama dukungan keluarga serta tenaga kesehatan.",d:["h-ikat-unta"]},
{q:"Bila beban terasa berat berkepanjangan, langkah yang dianjurkan modul adalah…",
 opts:["Memendam sendiri","Meminta bantuan — kepada keluarga dan tenaga kesehatan jiwa","Menunggu hilang sendiri","Menjauhi semua orang"],a:1,
 ex:"Meminta bantuan adalah keberanian, bukan kelemahan; penilaian dan penanganan ada pada profesional."},
{q:"Sabar dan salat dalam Al-Baqarah 2:153 diposisikan sebagai…",
 opts:["Beban tambahan","Penolong (isti‘anah) bagi jiwa","Pengganti dokter","Syarat kehamilan"],a:1,
 ex:"“Mohonlah pertolongan dengan sabar dan salat” — keduanya sumber kekuatan jiwa, beriringan dengan ikhtiar lahir.",d:["q-baqarah-2-153"]}],

"T3-04":[
{q:"Prinsip Qur’ani untuk pola makan ibu hamil dalam modul ini adalah…",
 opts:["Makan sebanyak-banyaknya","Halal lagi baik, tanpa berlebihan","Puasa ketat","Hanya suplemen"],a:1,
 ex:"Al-Baqarah 2:168 (halalan tayyiban) dan Al-A’raf 7:31 (makan-minum tanpa berlebihan) menjadi bingkai utama.",d:["q-baqarah-2-168","q-araf-7-31"]},
{q:"Mengapa trimester ketiga disebut “puncak pembangunan otak”?",
 opts:["Otak berhenti tumbuh","Otak janin tumbuh pesat dari pasokan ibu lewat plasenta","Hanya tulang yang tumbuh","Karena mitos"],a:1,
 ex:"Trimester ini otak tumbuh pesat dari bahan yang dipasok ibu lewat plasenta (PMC8234848) — karena itu kualitas asupan penting."},
{q:"Sumber DHA yang baik untuk perkembangan otak janin adalah…",
 opts:["Ikan berlemak rendah merkuri atau alga","Permen","Minuman bersoda","Gorengan"],a:0,
 ex:"DHA terbaik dari ikan rendah merkuri atau mikroalga; ALA dari biji-bijian terserap kurang efisien (Frontiers in Nutrition 2024)."},
{q:"Sikap modul ini terhadap kurma menjelang persalinan adalah…",
 opts:["Wajib syar’i","Haram","Tradisi baik dengan isyarat kisah Maryam dan studi pendukung — takaran tetap bersama dokter","Pengganti obat"],a:2,
 ex:"Kisah Maryam (QS 19:25–26) dan studi (Al-Kuran 2011; Razali 2017) memberi dasar; kandungan gulanya tinggi sehingga kondisi gula darah dikonsultasikan.",d:["q-maryam-19-25-26"]},
{q:"Soal takaran suplemen (zat besi, dsb.), modul ini berpegang bahwa…",
 opts:["Semua ibu takarannya sama","Takaran ditetapkan dokter/bidan setelah memeriksa kondisi","Ikuti iklan","Tidak perlu sama sekali"],a:1,
 ex:"Anemia sangat umum (sekitar separuh ibu hamil di Asia Tenggara — WHO), namun takaran dan kondisi khusus adalah ranah dokter; modul sengaja tidak mencantumkan angka dosis."}],

"T3-05":[
{q:"Adab menyambut bayi yang paling kukuh sanadnya adalah…",
 opts:["Azan di telinga","Tahnik kurma, doa keberkahan, dan nama yang baik","Iqamah di telinga kiri","Memandikan dengan air bunga"],a:1,
 ex:"Tahnik dan doa keberkahan diriwayatkan muttafaqun ‘alaih (HR Bukhari no. 5467; Muslim no. 2145).",d:["h-tahnik"]},
{q:"Bagaimana status riwayat azan di telinga bayi?",
 opts:["Sahih mutawatir","Diperselisihkan: hasan menurut sebagian, dha’if menurut banyak ulama","Palsu seluruhnya","Ijma sunnah"],a:1,
 ex:"Riwayat Abu Rafi’ dinilai hasan oleh Tirmidzi namun dha’if oleh banyak pemeriksa karena ‘Ashim bin ‘Ubaidillah; sebagian ulama tetap menganjurkan, sebagian menilai tidak disyariatkan — keduanya mu’tabar.",d:["h-azan-bayi"]},
{q:"Riwayat iqamah di telinga kiri bayi tergolong…",
 opts:["Sahih","Hasan","Mawdu’ (palsu)","Mutawatir"],a:2,
 ex:"Para pemeriksa hadis menilai riwayat iqamah palsu — karena itu ditinggalkan, berbeda dengan azan yang diperselisihkan.",d:["h-azan-bayi"]},
{q:"Aqiqah menurut hadis Samurah dilakukan pada…",
 opts:["Hari pertama","Hari ketujuh, bersama cukur rambut dan penamaan","Usia satu tahun","Saat akil baligh"],a:1,
 ex:"“Disembelihkan pada hari ketujuhnya, dicukur rambutnya, dan diberi nama” (HR Abu Dawud no. 2838; Tirmidzi no. 1522 — sahih).",d:["h-aqiqah"]},
{q:"Doa “rabbi hablii…” memohon keturunan yang menyejukkan mata terdapat dalam…",
 opts:["Al-Furqan 25:74","Al-Ikhlas","Al-Kautsar","An-Nasr"],a:0,
 ex:"Al-Furqan 25:74 — doa ‘ibadurrahman untuk pasangan dan keturunan penyejuk mata; doa adalah ikhtiar hati, bukan jaminan otomatis.",d:["q-furqan-25-74","q-ali-imran-3-38"]}],

"T3-06":[
{q:"Inti modul “Satu Hari Penuh” adalah…",
 opts:["Jadwal kaku per menit","Merangkai kebiasaan kecil T3-01–T3-05 jadi ritme harian yang lentur","Menambah aktivitas baru sebanyak mungkin","Menghafal tabel"],a:1,
 ex:"Yang dirangkai adalah suara, sentuhan, ketenangan, gizi, dan doa — dalam ritme yang menyenangkan, bukan jadwal kaku."},
{q:"Apa yang mengubah rutinitas biasa menjadi ibadah?",
 opts:["Durasi panjang","Niat karena Allah","Biaya besar","Pengumuman ke orang lain"],a:1,
 ex:"“Sesungguhnya amal-amal bergantung pada niat” (HR Bukhari no. 1; Muslim no. 1907).",d:["h-niat"]},
{q:"Anjuran aktivitas fisik ACOG dalam modul ini berlaku untuk…",
 opts:["Semua kehamilan tanpa kecuali","Kehamilan tanpa komplikasi, dengan konsultasi","Hanya atlet","Trimester pertama saja"],a:1,
 ex:"ACOG menekankan evaluasi untuk kehamilan berkomplikasi — karena itu aktivitas fisik selalu dikonsultasikan dahulu."},
{q:"Setelah ikhtiar harian tertata, sikap yang diajarkan adalah…",
 opts:["Cemas mengendalikan segalanya","Bertawakal kepada Allah","Berhenti berikhtiar","Membandingkan dengan ibu lain"],a:1,
 ex:"Ikhtiar yang menyenangkan dan berdasar, lalu tawakal — bukan jaminan hasil (rangkaian dalil pada kartu: niat, halal-tayyib, dzikir).",d:["h-niat","q-rad-13-28"]},
{q:"Ritme harian yang baik menurut modul ini bersifat…",
 opts:["Kaku dan seragam untuk semua ibu","Lentur, disesuaikan ritme nyata ibu","Ditentukan media sosial","Berubah total tiap hari"],a:1,
 ex:"Adaptasi ke ritme nyata ibu adalah bagian dari desain — konsistensi yang lembut mengalahkan kesempurnaan yang memberatkan."}],

"2Y-01":[
{q:"Temuan kunci Romeo dkk. (2018) tentang bahasa anak adalah…",
 opts:["Jumlah kata satu arah paling penting","Giliran percakapan bolak-balik berkaitan dengan aktivasi area Broca","Layar mempercepat bicara","Bahasa hanya genetik"],a:1,
 ex:"Yang berkaitan dengan aktivasi Broca adalah percakapan dua arah (conversational turns) — lepas dari status ekonomi keluarga."},
{q:"Mengapa modul ini non-layar untuk anak di bawah ±18–24 bulan?",
 opts:["Layar mahal","Anak kecil sulit belajar dari layar (transfer deficit) — AAP","Layar membuat mata biru","Supaya hemat listrik"],a:1,
 ex:"Bayi-batita belajar dari manusia; transfer dari layar ke dunia nyata sangat lemah pada usia ini (AAP)."},
{q:"“Ar-Rahman… ‘allamahul-bayan” (55:3–4) menjadi bingkai bahwa…",
 opts:["Bicara itu sepele","Kemampuan menjelaskan (al-bayan) adalah karunia Allah yang dirawat","Bahasa asing wajib","Diam lebih utama"],a:1,
 ex:"Allah mengajarkan al-bayan kepada manusia — maka menumbuhkan bahasa anak adalah merawat karunia-Nya.",d:["q-rahman-55-3-4"]},
{q:"Teladan Nabi berbicara kepada anak kecil tampak pada…",
 opts:["Mengabaikan anak","Sapaan hangat “Ya Aba ‘Umair, ma fa‘alan-nughair?”","Hanya bicara dengan orang dewasa","Memerintah dengan keras"],a:1,
 ex:"Beliau menyapa adik kecil Anas dengan kunyah dan candaan lembut, menghibur kesedihannya (HR Bukhari no. 6129; Muslim no. 2150).",d:["h-abu-umair"]},
{q:"Cara membaca buku yang paling menumbuhkan bahasa adalah…",
 opts:["Membaca cepat tanpa jeda","Membaca dialogis: bertanya, menunggu, menanggapi","Menyuruh anak diam","Memutar audio buku"],a:1,
 ex:"Membaca dialogis (Whitehurst dkk. 1988) menjadikan anak ikut bercerita — bicara DENGAN anak, bukan sekadar PADA anak."}],

"2Y-02":[
{q:"Ungkapan “ajari anakmu berenang dan memanah” yang benar penyandarannya adalah…",
 opts:["Hadis sahih Bukhari","Perkataan (atsar) Umar bin Khattab","Ayat Al-Qur’an","Hadis qudsi"],a:1,
 ex:"Ini atsar Umar (Mushannaf Abdurrazzaq), bukan sabda Nabi; versi marfu’nya sangat lemah — nilai ketangkasan tetap didukung dalil sahih lain.",d:["a-umar-renang"]},
{q:"Dalil sahih yang mendukung nilai melatih ketangkasan adalah…",
 opts:["“Kekuatan itu memanah” — HR Muslim no. 1917","Riwayat palsu","Mimpi seorang tabi’in","Tidak ada"],a:0,
 ex:"Nabi menafsirkan “quwwah” dalam Al-Anfal 8:60 dengan memanah, tiga kali — dasar yang jujur bagi latihan fisik.",d:["h-irmi","h-mukmin-kuat"]},
{q:"Menurut Adolph & Tamis-LeMonda, gerak bagi batita adalah…",
 opts:["Gangguan belajar","Cara utama belajar dan mengeksplorasi dunia","Sekadar pembakaran kalori","Tanda hiperaktif"],a:1,
 ex:"Setiap merangkak dan memanjat adalah penelitian kecil anak terhadap dunianya."},
{q:"Sikap modul terhadap baby walker adalah…",
 opts:["Sangat dianjurkan","Tidak dianjurkan karena risiko cedera — konfirmasi dokter/bidan","Wajib dimiliki","Pengganti pengawasan"],a:1,
 ex:"Alat yang berisiko cedera dihindari; ruang lantai aman dan pendampingan jauh lebih bernilai."},
{q:"“Mukmin yang kuat lebih dicintai Allah…” (HR Muslim no. 2664) ditutup dengan perintah…",
 opts:["Berhenti berusaha","Bersemangat pada yang bermanfaat, minta tolong kepada Allah, jangan merasa lemah","Mengandalkan nasib","Menunda segalanya"],a:1,
 ex:"Merawat tubuh dan kemampuan anak adalah bagian dari merawat amanah kekuatan.",d:["h-mukmin-kuat"]}],

"2Y-03":[
{q:"Hadis Aisyah bermain boneka (HR Bukhari no. 6130; Muslim no. 2440) menunjukkan Nabi…",
 opts:["Melarang mainan","Membolehkan bahkan memfasilitasi teman-teman Aisyah bermain","Membakar boneka","Tidak peduli"],a:1,
 ex:"Bila teman-teman kecil itu bersembunyi, beliau justru mengirim mereka kembali untuk bermain bersama Aisyah.",d:["h-dolls-aisyah"]},
{q:"Soal boneka berwujud lengkap, peta fiqh yang jujur adalah…",
 opts:["Semua ulama mengharamkan","Semua ulama mewajibkan","Banyak fuqaha memberi rukhshah mainan anak; sebagian mensyaratkan bentuk tak utuh","Tidak pernah dibahas ulama"],a:2,
 ex:"Ibnu Hajar menukil pengecualian mainan anak dari larangan tashwir; pendapat lain mensyaratkan bentuk tidak utuh — keluarga memilih dengan ilmu.",d:["h-dolls-aisyah"]},
{q:"Menurut tinjauan Lillard dkk. (2013), main pura-pura adalah…",
 opts:["Penyebab tunggal kecerdasan","Salah satu jalan perkembangan, bukan jaminan","Berbahaya","Hanya untuk anak perempuan"],a:1,
 ex:"Modul jujur pada bukti: bermanfaat, namun bukan resep ajaib tunggal."},
{q:"Pesan al-Ghazali tentang melarang anak bermain adalah…",
 opts:["Mematikan hati dan menumpulkan kecerdasan anak","Mempercepat kedewasaan","Menambah hafalan","Tidak berdampak"],a:0,
 ex:"“Yumitu qalbahu wa yubthilu dzaka’ahu” — sembilan abad sebelum sains bermain modern (Ihya, Riyadhatus Shibyan).",d:["k-ghazali-main"]},
{q:"Peran orang tua dalam bermain imajinatif batita adalah…",
 opts:["Menyetir semua skenario","Mengikuti arahan anak dan menemani","Menonton dari jauh dengan ponsel","Mengoreksi setiap “kesalahan” cerita"],a:1,
 ex:"Dipimpin anak: ikuti idenya, tambahkan sedikit, dan biarkan imajinasinya memimpin."}],

"2Y-04":[
{q:"Temuan Bonawitz dkk. (2011) tentang mengajari balita secara langsung adalah…",
 opts:["Makin diajari makin eksploratif","Instruksi berlebihan justru menurunkan eksplorasi anak","Tidak ada efeknya","Balita tak bisa belajar sendiri"],a:1,
 ex:"Saat orang dewasa “mengajarkan semuanya”, anak berhenti menjelajah kemungkinan lain — cukup temani rasa ingin tahunya."},
{q:"“Sesungguhnya Kami menciptakan segala sesuatu menurut ukuran” adalah ayat…",
 opts:["Al-Qamar 54:49","Al-Fil 105:1","Quraisy 106:1","Al-Ma’un 107:1"],a:0,
 ex:"Al-Qamar 54:49 — keteraturan dan ukuran pada ciptaan menjadi pintu mengenalkan sebab-akibat serta pola kepada anak.",d:["q-qamar-54-49","q-furqan-25-2"]},
{q:"Tujuan jujur mengenalkan pola dan sebab-akibat pada batita adalah…",
 opts:["Mencetak jago matematika","Menanam benih kepekaan pola lewat main sehari-hari","Persiapan ujian","Mengejar kurikulum"],a:1,
 ex:"Modul menegaskan: menanam benih, bukan mencetak — kegembiraan menemukan adalah intinya, maknanya dipegang orang tua."},
{q:"Permainan sederhana yang melatih sebab-akibat di rumah misalnya…",
 opts:["Menonton video","Menjatuhkan benda aman ke wadah dan melihat hasilnya","Menghafal angka 1–100","Kartu pelajaran formal"],a:1,
 ex:"Aksi → akibat yang terlihat (memasukkan bentuk, menumpahkan, menumpuk) adalah laboratorium pertama anak."},
{q:"Tafakkur dalam Ali ‘Imran 3:190–191 mengajarkan bahwa rasa ingin tahu anak adalah…",
 opts:["Gangguan","Pintu menuju mengenal kebesaran Allah","Hal yang harus dipadamkan","Tanda nakal"],a:1,
 ex:"Memikirkan penciptaan langit dan bumi adalah ibadah akal — rasa ingin tahu anak dirawat ke arah itu, tanpa ceramah.",d:["q-ali-imran-3-190-191"]}],

"2Y-05":[
{q:"Temuan Zentner & Eerola (2010) tentang bayi dan irama adalah…",
 opts:["Bayi tak peduli irama","Bayi merespons ketukan secara alami — bawaan manusia","Irama berbahaya","Hanya bayi tertentu"],a:1,
 ex:"Respons pada ketukan adalah bawaan; karena itu tepukan dan senandung sederhana sudah sangat bernilai."},
{q:"Menurut Gerry & Trainor (2012), yang paling bermanfaat untuk batita adalah…",
 opts:["Audio pasif berjam-jam","Bermusik aktif dan bersama (bernyanyi, bertepuk)","Konser keras","Tidak ada musik sama sekali"],a:1,
 ex:"Kelas musik aktif-partisipatif lebih bermanfaat daripada sekadar memutar audio pasif."},
{q:"Peta khilaf alat musik yang jujur adalah…",
 opts:["Semua ulama membolehkan tanpa kecuali","Jumhur melarang ma‘azif berdasar HR Bukhari no. 5590; sebagian (Ibnu Hazm, dinukil pula dari sebagian ulama) membolehkan — keduanya dipetakan","Tidak pernah dibahas","Hanya soal selera"],a:1,
 ex:"Modul tidak berfatwa: hadis al-ma‘azif dan kritik atasnya disajikan adil; senandung, nasyid, dan duff diterima luas.",d:["h-maazif","h-eid-duff"]},
{q:"Dalil duff dan lagu gembira pada hari raya adalah…",
 opts:["HR Bukhari no. 949/952; Muslim no. 892","Riwayat palsu","Hanya logika","Tidak ada"],a:0,
 ex:"Dua anak perempuan bernyanyi dengan duff di rumah Aisyah; Nabi membiarkannya — “ini hari raya kita”.",d:["h-eid-duff"]},
{q:"Suara terbaik dan paling aman untuk batita menurut modul ini adalah…",
 opts:["Speaker keras","Suara pengasuh sendiri: senandung, nasyid, tartil","Televisi","Mainan elektronik nyaring"],a:1,
 ex:"Trehub: bayi menyimak nyanyian pengasuh lebih lama dan menatap mulut penyanyi — menunjang bahasa; lindungi pendengaran dari suara nyaring.",d:["q-muzzammil-73-4","h-attaghanni"]}],

"2Y-06":[
{q:"Sikap jujur modul terhadap bukti manfaat alam bagi anak (Chawla 2015) adalah…",
 opts:["Sudah pasti sebab-akibat","Menjanjikan namun banyak yang korelasional — bermanfaat, bukan jaminan","Tidak ada manfaat","Hanya mitos"],a:1,
 ex:"Cukup hadirkan pengalaman alam tanpa menceramahi dan tanpa klaim berlebihan."},
{q:"“Dan Allah mengeluarkan kamu dari perut ibumu… dan Dia menjadikan bagimu pendengaran, penglihatan, dan hati” adalah…",
 opts:["An-Nahl 16:78","Al-Lahab 111:1","Al-Kafirun 109:1","An-Nasr 110:1"],a:0,
 ex:"Indra adalah karunia yang disebut berurutan — main sensorik adalah cara mensyukurinya dengan melatihnya.",d:["q-nahl-16-78"]},
{q:"Ayat yang mengajak memperhatikan unta, langit, gunung, dan bumi adalah…",
 opts:["Al-Ghasyiyah 88:17–20","Al-Falaq","Al-Ikhlas","Al-Masad"],a:0,
 ex:"“Afala yanzhuruna ilal-ibili kaifa khuliqat…” — alam terbuka adalah ruang kelas tanda-tanda Allah.",d:["q-ghasyiyah-88-17-20","q-dzariyat-51-20-21"]},
{q:"Adab kepada hewan saat menjelajah alam bersumber dari…",
 opts:["Kasih pada makhluk berpahala (HR Bukhari/Muslim) dan larangan menzaliminya (kisah kucing)","Tidak ada tuntunan","Hanya budaya lokal","Aturan modern saja"],a:0,
 ex:"Memberi minum makhluk bernyawa berpahala; menzalimi hewan diancam — anak belajar lembut sejak dini.",d:["h-anjing","h-kucing"]},
{q:"Main sensorik (air, pasir, tanah) yang aman dilakukan dengan…",
 opts:["Tanpa pengawasan","Diawasi, bahan non-toksik, lalu cuci tangan","Di jalan raya","Memakai bahan tajam"],a:1,
 ex:"Dunia nyata adalah medianya; keamanan dan kebersihan adalah adabnya."}],

"2Y-07":[
{q:"Menurut Eisenberg dkk. (1998), merespons tangis dan distres anak secara sensitif akan…",
 opts:["Memanjakan","Membangun rasa aman dan kemampuan regulasi — sebuah investasi","Membuat cengeng permanen","Tidak berpengaruh"],a:1,
 ex:"Respons hangat yang konsisten mengajari sistem saraf anak bahwa dunia aman dan emosi bisa diatur."},
{q:"Langkah pertama menenangkan anak yang tantrum adalah…",
 opts:["Berteriak lebih keras","Menenangkan diri sendiri dulu (ko-regulasi)","Meninggalkannya sendirian lama","Memberi gawai"],a:1,
 ex:"Anak meminjam ketenangan dari pengasuhnya; ketenangan Anda adalah alat utamanya."},
{q:"“Allah Mahalembut dan mencintai kelembutan dalam segala urusan” diriwayatkan dalam…",
 opts:["HR Bukhari no. 6024; Muslim no. 2165","Riwayat palsu","Hanya kata mutiara","Injil"],a:0,
 ex:"Rifq adalah inti adab pengasuhan — dan kelembutan menghiasi segala sesuatu (HR Muslim no. 2594).",d:["h-rifq"]},
{q:"Saat Aqra’ bin Habis heran Nabi mencium cucunya, beliau menjawab…",
 opts:["“Siapa tidak menyayangi, tidak disayangi”","“Itu kebiasaan buruk”","“Anak tak perlu kasih sayang”","Diam saja"],a:0,
 ex:"“Man la yarham la yurham” (HR Bukhari no. 5998; Muslim no. 2317) — kasih sayang fisik kepada anak adalah sunnah.",d:["h-rahmah-cium","h-laysa-minna"]},
{q:"“Orang kuat bukanlah yang menang gulat…” melainkan…",
 opts:["Yang paling kaya","Yang menguasai dirinya ketika marah","Yang paling keras suaranya","Yang tak pernah marah"],a:1,
 ex:"HR Bukhari no. 6114; Muslim no. 2609 — regulasi diri orang tua adalah teladan regulasi bagi anak; dan wasiat ringkasnya: “jangan marah” (HR Bukhari no. 6116).",d:["h-quwwah","h-la-taghdab"]}],

"2Y-08":[
{q:"Bandura menunjukkan anak belajar perilaku sosial terutama lewat…",
 opts:["Ceramah panjang","Meniru teladan — bahkan peniruan tertunda sejak 9–14 bulan","Hukuman","Hafalan"],a:1,
 ex:"Anak merekam dan menirukan yang dilihatnya, bahkan sebelum paham kata — teladan adalah kurikulum pertama."},
{q:"Menurut Warneken & Tomasello (2013), dorongan menolong pada batita tumbuh dengan…",
 opts:["Instruksi keras","Teladan dan pendampingan lembut — dorongan menolong sudah ada secara alami","Hadiah uang","Ancaman"],a:1,
 ex:"Batita menolong secara intrinsik; yang dibutuhkan adalah teladan dan kesempatan, bukan paksaan."},
{q:"“Sesungguhnya aku diutus untuk menyempurnakan akhlak yang mulia” berstatus…",
 opts:["Sahih (HR Ahmad no. 8952; al-Adab al-Mufrad)","Palsu","Lemah sekali","Bukan hadis"],a:0,
 ex:"Disahihkan al-Albani dan al-Arna’uth — akhlaq adalah inti misi kenabian, maka inti tarbiyah.",d:["h-akhlaq-misi","q-qalam-68-4"]},
{q:"Adab makan diajarkan Nabi kepada Umar bin Abi Salamah dengan cara…",
 opts:["Menghukum di depan umum","Tiga kalimat singkat di momen nyata: sebut nama Allah, makan dengan tangan kanan, dari yang terdekat","Ceramah satu jam","Menuliskannya saja"],a:1,
 ex:"HR Bukhari no. 5376; Muslim no. 2022 — singkat, hangat, tepat momen: model pengajaran adab untuk anak.",d:["h-umar-abi-salamah"]},
{q:"Mengapa janji kecil kepada anak (“kemari, kuberi sesuatu”) tidak boleh diingkari?",
 opts:["Karena dicatat sebagai dusta bila tak ditepati (al-Adab al-Mufrad no. 387; Abu Dawud no. 4991)","Tidak apa-apa diingkari","Anak cepat lupa","Hanya sopan santun budaya"],a:0,
 ex:"Menepati janji pada anak adalah adab pertama — kejujuran orang tua adalah pelajaran kejujuran anak.",d:["h-adab-janji"]}],

"2Y-09":[
{q:"Menurut Selman & Dilworth-Bart (2024), rutinitas yang dapat diprediksi memberi anak…",
 opts:["Kebosanan","Rasa aman dan latihan regulasi — anak tahu apa yang terjadi berikutnya","Kekangan","Tidak ada manfaat"],a:1,
 ex:"Prediktabilitas menurunkan kecemasan dan melatih pengaturan diri; sebagian besar buktinya korelasional, maka jaga ritme yang lentur."},
{q:"Amal yang paling dicintai Allah menurut hadis adalah…",
 opts:["Yang paling besar sekali jalan","Yang paling ajek (kontinu) meskipun sedikit","Yang paling terlihat orang","Yang paling mahal"],a:1,
 ex:"HR Bukhari no. 6464; Muslim no. 782 — fondasi membangun kebiasaan: kecil, konsisten, berkelanjutan.",d:["h-istiqamah"]},
{q:"“Beramallah sesuai kemampuan kalian…” (HR Bukhari no. 43) mengajarkan rutinitas dibangun dengan…",
 opts:["Memaksakan target besar","Moderasi: jangan membebani melebihi kesanggupan","Meniru keluarga lain persis","Tanpa rencana"],a:1,
 ex:"Allah tidak bosan sampai kalian bosan — moderasi menjaga rutinitas tetap hidup.",d:["h-makamampu"]},
{q:"Cara menanam rutinitas baru pada batita yang dianjurkan modul adalah…",
 opts:["Mengubah semuanya dalam semalam","Sedikit demi sedikit, satu jangkar kebiasaan pada waktu yang sama","Menunggu anak besar","Memakai hukuman"],a:1,
 ex:"Satu kebiasaan kecil di waktu yang ajek (mis. doa sebelum tidur) lebih kuat daripada jadwal besar yang cepat padam."},
{q:"Poster atau kartu rutinitas berfungsi sebagai…",
 opts:["Penentu utama keberhasilan","Pengingat — kuncinya konsistensi orang tua","Pengganti pendampingan","Hiasan wajib"],a:1,
 ex:"Rutinitas dibangun lewat konsistensi orang tua, bukan barang."}],

"P-01":[
{q:"Mekanisme utama anak belajar dari Anda menurut modul fondasi diri adalah…",
 opts:["Ceramah","Meniru Anda dan diregulasi oleh kehadiran Anda","Buku teks","Aplikasi"],a:1,
 ex:"Bandura (peniruan) dan ko-regulasi: keteladanan serta ketenangan Anda adalah mekanismenya."},
{q:"Konsep “good-enough parent” (Winnicott) selaras dengan hadis…",
 opts:["“Beramallah sesuai kemampuan” (HR Bukhari no. 43)","Riwayat palsu","Tidak ada kaitannya","Hadis tentang perang"],a:0,
 ex:"Cukup baik, bukan sempurna — mengejar sempurna menghalangi kehangatan dan tidak berkelanjutan.",d:["h-makamampu"]},
{q:"Temuan FPG/UNC tentang emosi pengasuh adalah…",
 opts:["Emosi tidak menular","Ketenangan Anda menenangkan anak; stres berat menambah agitasinya","Anak kebal stres","Stres baik untuk anak"],a:1,
 ex:"Regulasi diri orang tua adalah lingkungan emosional pertama anak."},
{q:"“Mengapa kamu mengatakan apa yang tidak kamu kerjakan?” adalah teguran dalam…",
 opts:["As-Saff 61:2–3","Al-Kautsar","Al-Fil","Quraisy"],a:0,
 ex:"Keselarasan kata dan perbuatan adalah inti keteladanan — bersama uswah hasanah (Al-Ahzab 33:21).",d:["q-saff-61-2-3","q-ahzab-33-21"]},
{q:"Bila Anda kewalahan berkepanjangan, langkah yang dianjurkan adalah…",
 opts:["Memendam","Mencari dukungan (keluarga, profesional) — bagian dari merawat fondasi","Menyalahkan anak","Berhenti mengasuh"],a:1,
 ex:"Merawat diri adalah merawat fondasi pengasuhan; meminta bantuan adalah kekuatan."}],

"P-02":[
{q:"Dalam modul ini, daftar 9 ranah kecerdasan dipakai sebagai…",
 opts:["Label permanen anak","Alat periksa agar tak ada ranah terlantar","Sains final yang baku","Tes IQ"],a:1,
 ex:"Waterhouse (2006) mengkritik MI sebagai teori; kita memakainya hanya sebagai checklist kepedulian, bukan label."},
{q:"Klaim “0–3 tahun menentukan segalanya” menurut Bruer (1999) adalah…",
 opts:["Fakta mutlak","Mitos — perkembangan berlanjut seumur hidup","Hukum biologi","Ijma ilmuwan"],a:1,
 ex:"Masa dini penting, tetapi bukan vonis; sikap yang benar tenang dan konsisten, bukan panik."},
{q:"“Dan Allah mengeluarkan kamu… tidak mengetahui apa pun, lalu Dia beri pendengaran, penglihatan, dan hati” menegaskan bahwa…",
 opts:["Anak lahir sudah tahu segalanya","Kemampuan tumbuh bertahap sebagai karunia — sejalan perkembangan","Indra tidak penting","Belajar sia-sia"],a:1,
 ex:"An-Nahl 16:78 dan As-Sajdah 32:9 — pertumbuhan bertahap adalah desain penciptaan.",d:["q-nahl-16-78","q-sajdah-32-9","q-qamar-54-49"]},
{q:"Sikap sehat terhadap variasi milestone anak adalah…",
 opts:["Panik bila beda seminggu dari tetangga","Memahami rentang wajar, dan memeriksakan penglihatan-pendengaran sejak dini bila ragu","Mengabaikan semua tanda","Membandingkan terus-menerus"],a:1,
 ex:"Rentang perkembangan itu lebar; kekhawatiran spesifik dibawa ke tenaga kesehatan, bukan ke kolom komentar."},
{q:"Tujuan “lensa perkembangan” bagi orang tua adalah…",
 opts:["Menilai anak orang lain","Memilih dan menilai aktivitas secara jujur sesuai tahap anak","Membuat rapor harian","Mengejar tren"],a:1,
 ex:"Dengan lensa yang jujur, Anda memilih aktivitas yang pas — tidak terlalu mudah, tidak memaksa."}],

"P-03":[
{q:"Prinsip scaffolding (Vygotsky, ZPD) berarti memberi anak…",
 opts:["Tugas yang mustahil","Tantangan pas dengan sedikit bantuan, tanpa frustrasi","Jawaban langsung selalu","Tidak ada tantangan"],a:1,
 ex:"Zona perkembangan proksimal: cukup menantang, ditopang secukupnya, lalu topangan dikurangi."},
{q:"Temuan Lepper (1973) dan Deci dkk. (1999) tentang hadiah adalah…",
 opts:["Hadiah selalu memperkuat","Hadiah eksternal bisa melemahkan motivasi intrinsik untuk hal yang sudah disukai — pujilah usaha","Anak tak butuh motivasi","Hukuman lebih baik"],a:1,
 ex:"Untuk aktivitas yang sudah dicintai anak, imbalan eksternal justru menggesernya; pujian atas usaha menguatkan."},
{q:"“Yassiru wala tu‘assiru, wabasysyiru wala tunaffiru” adalah pedagogi kenabian yang berarti…",
 opts:["Persulit agar kuat","Permudah dan gembirakan, jangan persulit dan jangan membuat lari","Diam saja","Hukum dulu baru ajari"],a:1,
 ex:"HR Bukhari no. 69; Muslim no. 1734 — bersama “agama itu mudah” (HR Bukhari no. 39).",d:["h-yassiru","h-dinyusr"]},
{q:"Kisah Mu‘awiyah bin al-Hakam (HR Muslim no. 537) menunjukkan Nabi mengoreksi dengan…",
 opts:["Bentakan dan hardikan","Tanpa membentak dan tanpa mempermalukan — “sebaik-baik pengajar”","Hukuman fisik","Mengusir"],a:1,
 ex:"Koreksi yang menjaga martabat justru membuat ilmu melekat dan hati terbuka.",d:["h-muawiyah"]},
{q:"Waktu terbaik mengajarkan adab kepada anak menurut teladan Nabi adalah…",
 opts:["Momen nyata saat kejadian, dengan kalimat singkat","Kuliah formal mingguan","Saat anak tidur","Lewat hukuman"],a:0,
 ex:"Seperti pada Umar bin Abi Salamah saat makan (HR Bukhari no. 5376; Muslim no. 2022) — singkat, hangat, kontekstual.",d:["h-umar-abi-salamah"]}],

"P-04":[
{q:"Urutan derajat riwayat dari kuat ke palsu adalah…",
 opts:["Sahih → hasan → da’if → mawdu’","Mawdu’ → sahih → hasan → da’if","Hasan → sahih → mawdu’ → da’if","Semua setara"],a:0,
 ex:"Ilmu mustalah menilai rantai dan isi: sahih (kuat), hasan (baik), da’if (lemah), mawdu’ (palsu)."},
{q:"“Periksalah dengan teliti bila orang fasik membawa berita” adalah perintah tabayyun dalam…",
 opts:["Al-Hujurat 49:6","Al-Lahab","An-Nashr","Al-Kafirun"],a:0,
 ex:"Bersama Al-Isra 17:36 — jangan mengikuti apa yang kau tak punya ilmu tentangnya.",d:["q-hujurat-49-6","q-isra-17-36"]},
{q:"“Sesungguhnya ilmu ini adalah agama, maka perhatikanlah dari siapa kalian mengambil agama kalian” adalah perkataan…",
 opts:["Muhammad bin Sirin","Abu Jahal","Orientalis","Tidak diketahui"],a:0,
 ex:"Muqaddimah Sahih Muslim — bersama Ibnul Mubarak: “Isnad adalah bagian dari agama.”",d:["a-ibnu-sirin","a-ibnul-mubarak"]},
{q:"Ancaman bagi yang sengaja berdusta atas nama Nabi adalah…",
 opts:["Tidak ada","“Hendaklah ia menyiapkan tempat duduknya di neraka” — hadis mutawatir","Hanya teguran ringan","Denda"],a:1,
 ex:"HR Bukhari no. 110; Muslim no. 3 — karena itu derajat riwayat wajib dijujurkan sebelum disebarkan.",d:["h-kadzib-nabi"]},
{q:"Langkah literasi saat menerima kabar parenting viral adalah…",
 opts:["Langsung bagikan","Telusuri sumber asli, cek bukti dan konsensus, waspadai yang tanpa rujukan","Percaya bila banyak likes","Tanya kolom komentar"],a:1,
 ex:"Tabayyun modern: sumber primer dahulu, baru kesimpulan — untuk sains maupun dalil."}],

"P-05":[
{q:"Ko-regulasi (Siegel & Bryson) berarti…",
 opts:["Anak wajib tenang sendiri","Anak meminjam ketenangan dari Anda karena belum mampu menenangkan diri","Mengabaikan tangisan","Menyuap dengan hadiah"],a:1,
 ex:"Sistem regulasi anak masih dibangun; kehadiran tenang Anda adalah perancahnya."},
{q:"Inti membaca dialogis (Whitehurst) adalah…",
 opts:["Membaca cepat sampai habis","Bertanya, menunjuk, menunggu, menanggapi — anak ikut bercerita","Anak menyimak diam","Menghafal teks"],a:1,
 ex:"Buku menjadi percakapan dua arah, bukan dongeng satu arah."},
{q:"Yang paling dibutuhkan lingkungan main batita menurut modul ini adalah…",
 opts:["Mainan sebanyak mungkin","Ruang aman sederhana dan kehadiran Anda","Gawai edukasi","Ruangan mewah"],a:1,
 ex:"Relasi mengalahkan barang; ruang aman membuat eksplorasi leluasa."},
{q:"“Innamal-a‘malu binniyyat” menjadikan keterampilan harian bernilai ibadah bila…",
 opts:["Diumumkan","Diniatkan karena Allah","Mahal biayanya","Difoto"],a:1,
 ex:"HR Bukhari no. 1; Muslim no. 1907 — niat mengubah rutinitas menjadi amal.",d:["h-niat"]},
{q:"Pola yang lebih dicintai dalam membangun keterampilan harian adalah…",
 opts:["Ledakan semangat sepekan lalu padam","Konsistensi lembut meski sedikit","Menunggu mood","Meniru orang lain persis"],a:1,
 ex:"Amal yang ajek meski sedikit (HR Bukhari no. 6464; Muslim no. 782) — bersama kelembutan (rifq) yang dicintai Allah.",d:["h-istiqamah","h-rifq"]}],

"P-06":[
{q:"Temuan Roskam & Mikolajczak tentang kelelahan orang tua adalah…",
 opts:["Tidak ada istilah burnout orang tua","Burnout orang tua nyata — yang kelelahan sulit hadir dengan sabar","Kelelahan tanda lemah iman","Hanya terjadi pada ibu"],a:1,
 ex:"Mengisi ulang diri adalah investasi untuk anak, bukan keegoisan."},
{q:"“Allah tidak membebani seseorang melainkan sesuai kesanggupannya” adalah…",
 opts:["Al-Baqarah 2:286","Al-Fil 105:1","Al-Ma’un 107:1","Al-Kautsar 108:1"],a:0,
 ex:"Dasar ilahiah untuk menakar beban — bukan dalih malas, melainkan izin untuk realistis.",d:["q-baqarah-2-286"]},
{q:"Nasihat Salman kepada Abu Darda yang dibenarkan Nabi berbunyi…",
 opts:["“Beribadahlah tanpa tidur”","“Berikan setiap pemilik hak akan haknya” — tubuh, keluarga, dan Rabb-mu punya hak","“Tinggalkan keluargamu”","“Bekerja tanpa henti”"],a:1,
 ex:"HR Bukhari no. 1968 — keseimbangan adalah sunnah, bukan kompromi.",d:["h-salman","h-jasad-haq"]},
{q:"Untuk urusan dunia, hadis menganjurkan melihat kepada…",
 opts:["Yang di atasmu agar iri","Yang di bawahmu — agar tidak meremehkan nikmat Allah","Media sosial","Tetangga terkaya"],a:1,
 ex:"HR Muslim no. 2963 — syukur menjaga jiwa orang tua dari jebakan membanding-bandingkan.",d:["h-unzhuru"]},
{q:"Bila beban terasa berat berkepanjangan, modul menyebut mencari bantuan profesional sebagai…",
 opts:["Kelemahan","Langkah berani — bagian dari merawat amanah","Aib keluarga","Pemborosan"],a:1,
 ex:"Wellbeing Anda adalah penopang pengasuhan; agama ini mudah (HR Bukhari no. 39).",d:["h-dinyusr"]}],

"P-07":[
{q:"“Setiap anak dilahirkan di atas fitrah…” (HR Bukhari no. 1358; Muslim no. 2658) berarti tugas orang tua adalah…",
 opts:["Menciptakan fitrah dari nol","Merawat dan menjaga fitrah yang sudah Allah tanamkan","Mengabaikannya","Menggantinya"],a:1,
 ex:"Anak lahir dengan kecenderungan tauhid dan kebaikan; lingkunganlah yang membentuk arah berikutnya.",d:["h-fitrah"]},
{q:"“Kullukum ra‘in…” menegaskan orang tua adalah…",
 opts:["Penonton","Pemimpin yang akan dimintai pertanggungjawaban atas yang dipimpinnya","Pemilik mutlak anak","Bebas tanggung jawab"],a:1,
 ex:"HR Bukhari no. 7138; Muslim no. 1829 — bersama perintah menjaga keluarga dari api (At-Tahrim 66:6).",d:["h-rain","q-tahrim-66-6"]},
{q:"Urutan sikap yang diajarkan Ali ‘Imran 3:159 adalah…",
 opts:["Tawakal tanpa tekad","Bulatkan tekad (azam), lalu bertawakal kepada Allah","Ragu terus-menerus","Mengandalkan orang lain"],a:1,
 ex:"“Fa idza ‘azamta fatawakkal ‘alallah” — ikhtiar sungguh-sungguh, lalu hati berserah.",d:["q-ali-imran-3-159"]},
{q:"Dalam perumpamaan modul integrasi, peran orang tua dan Allah adalah…",
 opts:["Orang tua menumbuhkan segalanya","Orang tua menanam dan menyiram; Allah yang menumbuhkan","Allah tidak terlibat","Anak tumbuh sendiri tanpa sebab"],a:1,
 ex:"Ini menjaga hati: bekerja sepenuh hati tanpa kecemasan ingin mengendalikan hasil."},
{q:"Yang menjaga arah seluruh jalur P-01 sampai P-07 saat Anda lelah adalah…",
 opts:["Niat karena Allah","Pujian orang","Target media sosial","Perbandingan dengan keluarga lain"],a:0,
 ex:"Niat (HR Bukhari no. 1) mengubah pengasuhan menjadi ibadah jangka panjang.",d:["h-niat"]}],

"PP":[
{q:"“Kullukum ra‘in” dalam panduan pasangan berarti tanggung jawab anak…",
 opts:["Hanya pada ibu","Hanya pada ayah","Dipikul kedua orang tua bersama","Pada kakek-nenek"],a:2,
 ex:"Suami pemimpin di keluarganya, istri penanggung jawab di rumah suaminya — keduanya ra‘in (HR Bukhari no. 893/7138; Muslim no. 1829).",d:["h-rain"]},
{q:"Al-Baqarah 2:233 mengajarkan keputusan tentang anak (mis. penyapihan) diambil dengan…",
 opts:["Sepihak","Kerelaan berdua dan musyawarah (‘an taradhin minhuma wa tasyawur)","Undian","Mengikuti tren"],a:1,
 ex:"Musyawarah pasangan adalah prinsip Qur’ani — bersama Asy-Syura 42:38.",d:["q-baqarah-2-233","q-syura-42-38"]},
{q:"Fondasi pernikahan dalam Ar-Rum 30:21 adalah…",
 opts:["Mawaddah dan rahmah (cinta dan kasih sayang)","Persaingan","Harta","Status sosial"],a:0,
 ex:"Ketenteraman (sakinah), cinta, dan kasih — rumah yang tenang adalah lingkungan tumbuh terbaik anak; “mereka pakaian bagimu…” (Al-Baqarah 2:187).",d:["q-rum-30-21","q-baqarah-2-187"]},
{q:"Sikap sistem TARBIYAH terhadap perbedaan pendapat fiqh adalah…",
 opts:["Berfatwa satu pendapat","Memetakan pendapat ulama secara adil tanpa berfatwa — keluarga memilih dengan ilmu","Mengabaikan fiqh","Mengikuti suara terbanyak"],a:1,
 ex:"Setiap klaim bersumber, kekuatan sains dijujurkan, derajat hadis disebut; medis dirujuk ke dokter."},
{q:"Dua hal yang tak bisa ditawar dalam kesepakatan pasangan ini adalah…",
 opts:["Nilai rapor dan les","Kesejahteraan-kegembiraan anak (lewat bermain, tanpa paksaan) dan non-layar di fase awal","Mainan mahal dan gadget","Jadwal padat"],a:1,
 ex:"Semua lewat bermain dan kehangatan; non-layar sejalan anjuran untuk usia di bawah ±18–24 bulan."}]
};
